In [2]:
from selenium import webdriver
from selenium.webdriver.support.ui import Select
import chromedriver_autoinstaller
import pandas as pd
from time import sleep

In [3]:
chromedriver_autoinstaller.install(path="../utils/")

'/Users/choidamian/Chaebol/utils/101/chromedriver'

# 2019

In [5]:
year = 2019

In [4]:
driver = webdriver.Chrome()
driver.implicitly_wait(3)
grsrch_url = 'https://www.kisline.com/cm/CM0100M00GE00.nice'
username = 'wonbok'
password = 'gkrtkrhk5034!'
driver.get(grsrch_url)
driver.find_element_by_class_name('btn_close_layer').click()
driver.find_element_by_id('lgnuid').send_keys(username)
driver.find_element_by_id('tmp_lgnupassword').click()
driver.find_element_by_id('lgnupassword').send_keys(password)
driver.find_element_by_class_name('btn_log_in').click()
sleep(3)
driver.find_element_by_link_text('로그아웃').click()
driver.quit()

In [6]:
df = pd.read_excel(f'../data/cmpnySumry/cmpnySumry{year}Eng.xlsx')

In [7]:
df.head()

,publicYm,fisclYr,unityGrupNm,entrprsNm,rprsntvNm,fondDe,grinil,indutyCode,indutyNm,ordtmEmplyCo,...,entrprsOthbcDe,assetsTotamt,debtTotamt,caplTotamt,caplAmount,selngAmount,thstrmNtpfAmount,reconstrctur,jurirno,year2
0,201905,2018,DB,디비생명보험(주),이태운,1989/04/14,1997/01/03,K65,보험 및 연금업,563,...,NaN,"10,887,144","10,296,289","590,855","193,331","2,180,825","24,637",금융보험업,1101110623606,2019
1,201905,2018,DB,디비금융서비스(주),황원기,2014/01/13,2014/03/01,K66,금융 및 보험관련 서비스업,30,...,NaN,"6,057","2,460","3,597","14,001","13,311","-2,499",금융보험업,1101115314474,2019
2,201905,2018,DB,디비에프아이에스(주),강운식,2014/12/01,2018/06/01,J62,"컴퓨터 프로그래밍, 시스템 통합 및 관리업",217,...,NaN,"47,579","5,854","41,725","1,000","47,269","12,063",일반회사,1101115576727,2019
3,201905,2018,DB,디비금융투자(주),고원종,1982/12/20,1982/12/20,K66,금융 및 보험관련 서비스업,892,...,1988/06/27,"5,428,689","4,794,353","634,336","212,232","725,156","46,854",금융보험업,1101110339956,2019
4,201905,2018,DB,디비인베스트(주),최경진,2009/11/16,2010/01/04,M71,전문 서비스업,1,...,NaN,"14,912","17,943","-3,031","306,500",933,-267,일반회사,1101114220359,2019

In [16]:
df_1 = pd.read_excel(f'../data/cmpnySumry/cmpnySumry{year+1}Eng.xlsx')
df_1[['jurirno', 'rcmgCode']]

            jurirno      rcmgCode
0     1345140003989  1.802408e+09
1     1345140003989  1.802408e+09
2     1101140192605  1.803409e+09
3     1754140000582  2.102105e+09
4     1760140002014  2.102105e+09
...             ...           ...
2279  1101110018443  8.701530e+05
2280  1101111758600  1.159730e+05
2281  1101112105561  1.788720e+05
2282  1101110016728  8.700720e+05
2283  1101117291597  2.103504e+09

[2284 rows x 2 columns]

In [19]:
df = df.merge(df_1[['jurirno', 'rcmgCode']], on='jurirno', how='left')

In [21]:
dfTrgt = df[df['rcmgCode'].isna()]
dfTrgt

,publicYm,fisclYr,unityGrupNm,entrprsNm,rprsntvNm,fondDe,grinil,indutyCode,indutyNm,ordtmEmplyCo,...,assetsTotamt,debtTotamt,caplTotamt,caplAmount,selngAmount,thstrmNtpfAmount,reconstrctur,jurirno,year2,rcmgCode
21,201905,2018,SM,(주)케이엘홀딩스이호,박도순,2013/09/12,2013/09/12,M73,"기타 전문, 과학 및 기술 서비스업",0,...,"123,266","62,713","60,553","18,560","14,191","9,224",일반회사,2001110378632,2019,NaN
23,201905,2018,SM,(주)동강시스타,김성원,2006/05/15,2019/04/01,I55,숙박업,111,...,"72,699","34,974","37,725","10,322","9,730","3,767",회생절차,1414110005851,2019,NaN
28,201905,2018,SM,회현상사(주),유창훈,1978/06/30,2018/07/01,L68,부동산업,0,...,"1,007",NaN,"1,007",500,NaN,17,일반회사,1101110231920,2019,NaN
31,201905,2018,SM,(주)에이본,한진아,2017/02/07,2017/02/07,G47,소매업; 자동차 제외,5,...,413,225,188,2,"12,204",184,일반회사,2850110346028,2019,NaN
35,201905,2018,SM,(주)에스엠티케미칼,박도순,2008/03/19,2008/03/19,G46,도매 및 상품 중개업,0,...,"103,473","55,128","48,345","23,539","8,460","5,417",일반회사,1701110351776,2019,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2081,201905,2018,효성,오원물산(주),허수창,1970/12/01,NaN,L68,부동산업,4,...,"28,575","26,628","1,947",600,"3,322",266,일반회사,1101110008478,2019,NaN
2083,201905,2018,효성,그랜드제칠차(주),정성훈,2013/07/04,2018/04/01,K64,금융업,0,...,"57,100","85,697","-28,597",0,0,"2,857",금융보험업,1101115175024,2019,NaN
2084,201905,2018,효성,오원엠앤아이(주),허수창,1995/01/01,NaN,L68,부동산업,24,...,"19,100","12,867","6,233","4,340","2,018",104,일반회사,1152110014923,2019,NaN
2085,201905,2018,효성,그랜드제육차(주),정성훈,2013/07/04,2018/04/01,K64,금융업,0,...,"15,285","22,002","-6,718",0,0,"1,113",금융보험업,1101115175173,2019,NaN
2097,201905,2018,효성,아이티엑스마케팅(주),전병무,2011/10/31,2012/01/02,K66,금융 및 보험관련 서비스업,14,...,"9,217","3,393","5,824","1,600","11,947",39,금융보험업,1101114718750,2019,NaN

In [10]:
driver = webdriver.Chrome()
driver.implicitly_wait(3)

grsrch_url = 'https://www.kisline.com/cm/CM0100M00GE00.nice'
username = 'wonbok'
password = 'gkrtkrhk5034!'
driver.get(grsrch_url)
driver.find_element_by_class_name('btn_close_layer').click()
driver.find_element_by_id('lgnuid').send_keys(username)
driver.find_element_by_id('tmp_lgnupassword').click()
driver.find_element_by_id('lgnupassword').send_keys(password)
driver.find_element_by_class_name('btn_log_in').click()
driver.implicitly_wait(3)
sleep(1)

dKiscode = dict()
inputElem = driver.find_element_by_id('q')

for jurirno in dfTrgt['jurirno']:
    
    if jurirno in dKiscode.keys():
        continue
        
    inputElem.send_keys(jurirno)
    driver.find_element_by_id('searchView').click()
    driver.implicitly_wait(3)
    target_row = driver.find_element_by_xpath('//*[@id="eprTable"]/tbody/tr/td[2]')
    kiscode = target_row.get_attribute('data-kiscode')
    dKiscode[jurirno] = kiscode
    print(f"{jurirno}: {kiscode}")
    sleep(3)
    inputElem = driver.find_element_by_id('q')
    inputElem.clear()

sleep(3)
driver.find_element_by_link_text('로그아웃').click()
sleep(1)
driver.quit()

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="eprTable"]/tbody/tr/td[2]"}
  (Session info: headless chrome=101.0.4951.64)

In [12]:
len(dKiscode)

176