In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
dfTrans20 = pd.read_excel('../data/transactions-mrg/2020/stacked.xlsx')
dfTrans20.head()

,매출회사,매입회사,매출액,국내계열사계(매출액),해외계열사계(매출액),국내매출액,해외매출액,매출액총계,year2,year,grpname2,매출사상/비,매출사금융/비금융,매출액Val,매입사상/비,매입사금융/비금융,grpname,grpcode,매출회사id,매입회사id
0,삼성전자,삼성물산,110238.0,2422149.0,130563681.0,20300939.0,134471920.0,154772859.0,2020,2019,삼성,상장,비금융,154772859.0,상장,비금융,samsung,511,380725,810053.0
1,삼성전자,삼성바이오에피스,4.0,2422149.0,130563681.0,20300939.0,134471920.0,154772859.0,2020,2019,삼성,상장,비금융,154772859.0,비상장,비금융,samsung,511,380725,18082125.0
2,삼성전자,삼성디스플레이,279363.0,2422149.0,130563681.0,20300939.0,134471920.0,154772859.0,2020,2019,삼성,상장,비금융,154772859.0,비상장,비금융,samsung,511,380725,18082126.0
3,삼성전자,세메스,7.0,2422149.0,130563681.0,20300939.0,134471920.0,154772859.0,2020,2019,삼성,상장,비금융,154772859.0,비상장,비금융,samsung,511,380725,314528.0
4,삼성전자,삼성전자서비스,453084.0,2422149.0,130563681.0,20300939.0,134471920.0,154772859.0,2020,2019,삼성,상장,비금융,154772859.0,비상장,비금융,samsung,511,380725,952133.0

In [3]:
dfTrans20[dfTrans20['매출회사id'].isna()]

Empty DataFrame
Columns: [매출회사, 매입회사, 매출액, 국내계열사계(매출액), 해외계열사계(매출액), 국내매출액, 해외매출액, 매출액총계, year2, year, grpname2, 매출사상/비, 매출사금융/비금융, 매출액Val, 매입사상/비, 매입사금융/비금융, grpname, grpcode, 매출회사id, 매입회사id]
Index: []

In [4]:
print(list(dfTrans20[dfTrans20['매입회사id'].isna()]['매입회사'].unique()))

['SKChinaCompany,Ltd', 'SKC&CBeijingCo.,Ltd', 'ESSENCORELimited', 'SKPharmtecoInc', 'SKSiltronAmerica,Inc', 'SKMaterialsJapanCo.,Ltd', 'SKBiotekIrelandLimited', 'SKBiotekUSA,Inc', 'SKMaterialsTaiwanCo.,Ltd', 'SKLifeScience,Inc', 'SKMaterialsJiangsuCo.,Ltd', 'SKUSA,Inc', 'SKE&PAmerica,Inc', 'SKBatteryHungaryKft', 'SKHI-TECHBATTERYMATERIALS(JIANGSU)CO.,LTD', 'SKShanghaiAsphaltCo.,Ltd', 'SKBATTERYAMERICA', 'JiangsuSKBatteryCertificationCenter', 'SKGlobalChemical(China)HoldingCo.,Ltd', 'SKGlobalChemicalSingaporePte.Ltd', 'NingboSKPerformanceRubberCo.,Ltd', 'SKGlobalChemicalJapanCo.,Ltd', 'SKPrimacorEurope,S.L.U', 'SKPrimacorAmericasLLC', 'SKGlobalChemicalInternationalTrading(Shanghai)Co.,Ltd', 'SKSaranAmericasLLC', 'SKGCAmericas,Inc', 'SKEnergyLubricants(Tianjin)Co.,Ltd', 'PT.PatraSK', 'SKLubricantsJapanCo.,Ltd', 'SKLubricantsEuropeB.V', 'SKGlobalChemicalInternationalTrading(Guangzhou)Co.,Ltd', 'SKLubricantsAmericas,Inc', 'SKEnergyInternationalPte,Ltd', 'SKEnergyEurope,Ltd', 'SKEnergyAmericasInc', 'SKtelecomJapanInc', 'FSKL&S(Shanghai)Co.,Ltd', 'HITECHSemiconductor(Wuxi)Co.,Ltd', 'HystarsSemiconductor(Wuxi)Co.Ltd', 'SKhynixsystemIC(Wuxi)Co.,Ltd', 'SKhynixSemiconductor(China)Ltd', 'SKhynixSemiconductor(Chongqing)Ltd', 'SKCEuropeGmbH', 'SKC,Inc', 'SKCInternationalShanghaiTradingCo.,Ltd', 'SKC(Jiangsu)HighTechPlastics', 'SKC(Nantong)PUSpecialtyCo.,Ltd', 'SKC(Nantong)SemiconductorMaterialsTechnologyCo.,Ltd', 'SKYHIGHMEMORYLIMITED', 'MCNSPolyurethanesEuropeSp.zo.o', 'SKCHi-Tech&Marketing(Suzhou)Co.,Ltd', 'SKBIOLANDHAIMENCO.,LTD', 'PrismEnergyInternationalPte.,Ltd', 'SKE&SAmericas,Inc', 'PrismEnergyInternationalChinaLimited', 'SKGasInternationalPte.Ltd', 'SKGasUSAInc', 'NanoenTekAmericaInc', 'LIFEDESIGNCOMPANYInc', 'SMCUS,INC', 'MCNSPolyurethanesMalaysiaSdnBhd', 'MCNSPolyurethanesUSAInc', 'MitsuiChemicals&SKCPolyurethanesInc', 'PT.MCNSPolyurethanesIndonesia', 'ThaiMitsuiSpecialtyChemicalsCo.,Ltd', 'TianjinCosmoPolyurethanesCo.,Ltd', 'MCNSPolyurethanesMexico,S.deR.L.deC.V', 'MCNSPolyurethanesIndiaPvt.Ltd', 'BeijingMitsuiChemicals&SKCPolyurethanesCo.,Ltd', 'FoshanMitsuiChemical&SKCPolyurethanesCo.,Ltd', 'SKGasTradingLLC', 'SKEngineering&Construction(Nanjing)Co.,Ltd', 'SBCGENERALTRADING&CONTRACTINGCO.W.L.L', 'AvrasyaTuneliIsletmeInsaatVeYatirimA.S', 'SilvertownInvestCoLtd', 'SKNETWORKSAMERICA,Inc', 'POSK(Pinghu)SteelProcessingCenterCo.,Ltd', 'SK(Guangzhou)MetalCo.,Ltd', 'SKNetworksDeutschlandGmbH', 'SKNetworksHongKongLtd', 'SKNetworksJapanCo.,Ltd', 'SKNetworks(Shanghai)Co.,Ltd', 'SKLubricants&OilsIndiaPvt.Ltd', 'SKLubricantsRusLimitedLiabilityCompany', 'SKNETWORKSRETAILSMALAYSIASDN.BHD', 'SKMaterialsXianCo.,Ltd', 'SKMaterialsShanghaiCo.,Ltd', 'AMPACFineChemicals,LLC', 'SKSiltronJapan,Inc', 'SOLMICSTAIWANCO.,LTD', 'SKCHi-Tech&MarketingTaiwanCo.,Ltd', 'SKCHi-Tech&MarketingPolskaSP.Z.O.O', 'AsiaBitumenTradingPte,Ltd', 'IBERIANLUBEBASEOILSCOMPANY,S.A', 'SKE&PCompany', 'SKE&POperationsAmerica,LLC', 'SKhynixAsiaPte.Ltd', 'SABICSKNexleneCompanyPte.Ltd', 'SKChemicals(Qingdao)Co.,Ltd', 'SKChemicalsAmerica', 'SKChemicals(Suzhou)Co.,Ltd', 'SKChemicalsGmbH', 'SKB&TPTE.LTD', 'SKhynix(Wuxi)SemiconductorSalesLtd', 'SKhynixAmericaInc', 'SKhynixDeutschlandGmbH', 'SKhynixItalyS.r.l', 'SKhynixJapanInc', 'SKhynixmemorysolutionsAmericaInc', 'SKhynixmemorysolutionsTaiwanLtd', 'SKhynixSemiconductor(Shanghai)Co.,Ltd', 'SKhynixSemiconductorHongKongLtd', 'SKhynixSemiconductorIndiaPrivateLtd', 'SKhynixSemiconductorTaiwanInc', 'SKhynixU.K.Ltd', 'FSKL&SHungaryKft', 'PHILKOUBINSLTD.CORP', 'SUZHOUHAPPYNARAECo.,Ltd', 'LGHoldingsJapanCo.,Ltd', 'VietnamLotteriaCo.,Ltd(vietnam', 'PT.LOTTERIAINDONESIA', 'JSCLotteRUS', 'PT.SJIndonesia', 'LotteDutyFreeGuam,LLC', 'LottePhuKhanhDutyFreeTradingCo.,Ltd', 'HAITHANH-LOTTECOMPANYLIMITED', 'LotteHotelGuamLLC', 'LotteHotelVietnamCompanyLimited', 'LotteDutyFreeKansaiCo.,Ltd', 'LotteDutyFreeJapanCo.,Ltd', 'LotteDutyFree(Thailand)Co.,Ltd', 'LotteHotelSaintPetersburg,LLC', 'LotteHotelAraiCo.,Ltd', 'LotteHotelHoldingsUSACo.,Ltd', 'LotteHotelNewYorkPalaceLLC', 'LotteHotelVladivostokLLC', 'LotteEuropeInvestmentB.V', '낙천(중국)식품유한공사', 'LOTTEQINGDAOFOODSCO.,LTD.,', '낙천(상해)식품유한공사', 'LotteConfectioneryRUSLLC', 'LotteIndiaCo.,Ltd.(제과', 'ChocolaterieGuylianN.V', 'LotteKolson(Pvt.)Limited', 'LotteConfectionery(S.E.A.)Pte.Ltd.,', 'RakhatJSC', 'LotteInternationalAmericaCorp', 'LotteVinaInternational', '낙천(중국)기업관리유한공사', 'LOTTELIQUORJAPANCO.,LTD', 'LOTTEBGAMERICACORP', '낙천주업(북경)유한공사', 'PEPSI-COLAPRODUCTSPHILIPPINES,INC', 'LOTTEVIETNAMSHOPPINGJOINTSTOCKCOMPANY', 'PT.LOTTESHOPPINGINDONESIA', 'LOTTESHOPPINGPLAZAVIETNAMCO.,LTD', 'LOTTEENTERTAINMENTVIETNAMCOMPANYLIMITED', 'LOTTEChemicalHungaryLtd', 'LOTTEADVANCEDMATERIALSEUROPEGMBH', 'LOTTEChemicalJapanCo.,Ltd', '낙천공정소료(심양)유한공사', 'LotteChemicalTitanHoldingBerhad', 'PTLOTTECHEMICALINDONESIA', 'LotteUBESyntheticRubberSdn.Bhd', '호석화학무역(상해)유한공사', '낙천공정소료(가흥)유한공사', 'Kor-UZGasChemicalInvestmentLtd', 'LotteChemicalUKLimited', 'LotteChemcialPolandSp.zo.o', 'LOTTECHEMICALNIGERIALIMITED', 'LotteChemicalAlabamaCorp', 'LotteChemicalUSACorporation', '낙천공정소료(합비)유한공사', '늑미상무(상해)유한공사', 'LOTTEFineChemicalEuropeGmbH', 'LOTTEFineChemicalTrading(Shanghai)Co.,Ltd', 'LOTTEPROPERTIES(CHENGDU)HKLIMITED', 'LOTTEChemicalVietnamCo.,Ltd', 'LotteChemicalTitan(M)Sdn.Bhd', 'LotteCinemaVietnamCo.,Ltd', 'LotteGloryProperties(Shenyang)Ltd', 'LOTTEPROPERTIESHANOICO.,LTD', 'LOTTEPROPERTIESHCMCCOMPANYLIMITED', 'LOTTECO.,LTD', 'PT.LotteMembersIndonesia', 'LotteMembersVietnamCo.,Ltd', 'LOTTEMGSBeverage(Myanmar)Co.,Ltd', 'LotteGlobalLogisticsVietnamCo.,Ltd', 'LotteGlobalLogisticsKazakhstanCo.Ltd', 'LOTTEGLOBALLOGISTICSPHILIPPINESINC', 'ShanghaiHyundaiAsiaShippingInternationalFreightForwardingCo.Ltd', 'LotteGlobalLogistics(Hongkong)Co.,Limited', 'LOTTEGLOBALLOGISTICS(INDIA)PRIVATELIMITED', 'LOTTEGLOBALLOGISTICS(SINGAPORE)PTE.LTD', 'LOTTEVINATRANSGLOBALLOGISTICS(VIETNAM)CO.,LTD', 'LOTTEGLOBALLOGISTICS(UK)CO.,LTD', 'LOTTEGLOBALLOGISTICS(NETHERLANDS)B.V', 'LOTTEGlobalLogistics(Germany)GmbH', 'LOTTEGLOBALLOGISTICS(USA),INC', 'LOTTEGLOBALLOGISTICS(NORTHAMERICA)INC', 'LotteRental(Vietnam)CompanyLimited', 'LOTTECORALISVIETNAMCOMPANYLIMITED', '요녕낙천초시유한공사', 'PT.LOTTEMARTINDONESIA', '낙천상업관리(천진)유한공사', '낙천백화(심양)유한공사', 'LotteInternationalDepartmentStore(Weihai)Co.,Ltd', 'PTLOTTESHOPPINGAVENUEINDONESIA', '낙천백화(천진)유한공사', '낙천백화(성도)유한공사', 'PTLotteChemicalTitanNusantara', 'LACC,LLC', '낙천신식기술(북경)유한공사', 'LOTTEDATACOMMUNICATIONCOMPANYLIMITEDVIETNAM', 'PT.LOTTEDATACOMMUNICATIONINDONESIA', 'LOTTE-HPTHIGHTECH.VIETNAMCOMPANYLIMITED', 'LotteFinanceVietnamCo.,Ltd', 'PT.DaehongCommunicationsIndonesia', '대홍광고(상해)유한공사', 'DAEHONGCOMMUNICATIONSVIETNAMCO.,LTD', 'LotteHotelBeverage(NYP)LLC', '낙천성건설(북경)유한공사', 'LotteE&CMalaysiaSdn.Bhd', 'CORALISS.A', '낙천지산(성도)유한공사', '낙천융자조임(중국)유한공사', '한화기계(소유한공사', '푸디스찬음관리(상해)유한공사', '한화토탈화공무역(상해)유한공사', '한화화학(상해)유한공사', '한화국제무역(상해)유한공사', 'HanwhaAdvancedMaterialsAmericaLLC', 'HanwhaAdvancedMaterialsBeijingCo.,Ltd', 'HanwhaAdvancedMaterialsEurope,s.r.o', 'HanwhaAdvancedMaterialsShanghaiCo.,Ltd', 'HanwhaAZDEL,Inc', 'HanwhaChemical(Ningbo)Co.,Ltd', 'HanwhaEuropeGmbH', 'HanwhaHongKongCo.,Ltd', 'HanwhaInternational(S)PteLtd', 'HanwhaInternationalLLC', 'HanwhaMachineryAmericas,Inc', 'HanwhaMiningServicesAustraliaPty.,Ltd', 'HanwhaQCELLSAmericaInc', 'HanwhaQCELLSCo.,Ltd.(Qidong', 'HanwhaQCELLSGmbh', 'HanwhaQCELLSJapanCo.,Ltd', 'HanwhaQCELLSMalaysiaSdn.Bhd', 'HANWHATECHMUSALLC', 'PT.BaraBumiInternational', 'PT.HanwhaMiningServicesIndonesia', 'S&PWorldNetworksDMCC', 'TRIENERGYGLOBALPTE.LTD', 'HanwhaTechwinEuropeLimited', 'HanwhaQCELLSTechnology(Shanghai)Co.,Ltd', 'HanwhaEnergyCorporationJapan', 'HanwhaQCELLSAmericasHoldings.Corp', 'HanwhaQCELLSAustraliaPtyLtd', 'HanwhaQCELLSEPCUSA,LLC', 'HanwhaMiningServicesChileSpA', 'HanwhaAdvancedMaterialsGermanyGmbH', '174PowerGlobalRetailTexas,LLC', 'HanwhaTechwinMiddleEastFZE', 'HanwhaTechwinSecurityVietnam', 'GSCaltexChinaCo.,Ltd', 'GSCaltexTrading(Suzhou)Co.,Ltd', 'GSCCzechs.r.o', 'GSC(Suzhou)PlasticsCo.,Ltd', 'GSCaltexIndiaPte.,Ltd', 'GSCaltex(Langfang)PlasticsCo.,Ltd', 'GSCaltexSingaporePte.,Ltd', 'GSLubricants(Tianjin)Co.,Ltd', 'GSCaltexMexicoS.deR.L.deC.V', 'GSGLOBALSINGAPOREPTE.LTD', 'GSGLOBALUSA,INC', 'GSGlobalJapanCo.,LTD', 'SYENERGYPTE.LTD', 'GSAromaticsPte.Ltd', 'QingdaoLidongChemicalCo.,Ltd', 'GS(상해)상무유한공사', 'PTGSGlobalResources', 'GSGlobal(Suzhou)SteelServiceCenterCo.,Ltd', 'GSGlobalAustrailiaPTY.LTD', 'GSGlobalEuropeGMBH', 'GSE&CNanjingCo.,Ltd', 'VietnamGSEnterpriseOneMemberLLC', 'GSE&CDelhiPvt.Ltd', 'GSEngineering&ConstructionMumbaiPvt.Ltd', 'GSConstructionArabiaCo.,Ltd', 'GSEngineering&ConstructionSpain,S.L', 'GSInimaEnvironmentS.A', 'GSEngineering&ConstructionAustraliaPtyLtd', 'PT.GSENCDevelopmentIndonesia', 'GSConstructionMiddleEastL.L.C', '청도삼양피혁유한공사', 'HyundaiHeavyIndustriesBrasil-ManufacturingandTradingofConstructionEquipment', 'HyundaiArabiaLLC', '현대중공(중국)투자유한공사', 'HyundaiConstructionEquipmentEuropeN.V', 'HyundaiConstructionEquipmentAmericas,Inc', 'HyundaiConstructionEquipmentIndiaPrivateLtd', '상주현대액압기기유한공사', '현대융자조임유한공사', '현대강소공정기계유한공사', '연대현대빙윤중공유한공사', 'HyundaiHeavyIndustriesCo.Bulgaria', 'HyundaiPowerTransformersUSA,Inc', '현대중공(중국)전기유한공사', 'Hyundai-VietnamShipbuildingCo.,Ltd.', 'HyundaiOilSingaporePte.Ltd', 'HyundaiOilbank(SHANGHAI)CO.,LTD', 'HyundaiGlobalServiceEuropeB.V', 'HyundaiGlobalServiceAmericasCo.,Ltd', 'HyundaiGlobalServiceSingaporePte.Ltd', 'HYUNDAIENERGYSOLUTIONSAMERICAINC', 'HYUNDAIROBOTICS(SHANGHAI)CO.,LTD', 'PT.HyundaiConstructionEquipmentAsia', '기이가무역(상해)유한공사', 'ShinsegaeInternationalVietnamCo.,Ltd', '상해이득무역유한공사', 'E-MARTAMERICA,INC', 'E-MARTVIETNAMCO.,LTD', 'PKRetailHoldingsInc', 'ChangTuhCorporation', 'SHINSEGAEMAMEESDN.BHD', 'CJVIETNAMCOMPANYLIMITED', 'HanjinInternationalCorp', 'HanjinInternationalJapan', 'TotalAviationServiceLLC', 'HanjinIntermodalAmericaInc', "WACINT'LLOGISTICSVIETNAMCONPANYLIMITED", 'HanjinGlobalLogistics(HongKong)Ltd', 'HanjinGlobalLogistics(Dalian)Ltd', 'QINGDAOHANJINLUHAIINTERNATIONALOGISTICSCO.,LTD', 'HANJINGLOBALLOGISTICS(SHANGHAI)LIMITED', 'HANJINGLOBALLOGISTICS(SHENZHEN)LIMITED', 'HANJINGLOBALLOGISTICSEUROPEs.r.o', 'HANJINGLOBALLOGISTICSMYANMARCO.,LTD', 'HANJINGLOBALLOGISTICS(VIETNAM)Ltd', 'GLSAP', "WACINT'LLOGISTICS(HKLIMITED", "WACINT'LLOGISTICS(QINGDAOCOMPANYLIMITED", 'DoosanMottrol(Jiangyin)Co.,Ltd', 'DoosanIndustrialVehicleAmericaCorp', 'DoosanFuelCellAmerica,Inc', 'DoosanIndustrialVehicleEuropeN.A', 'DoosanIndustrialVehicleYantaiCo.,Ltd', 'DoosanIndustrialVehicleU.K.Ltd', 'DoosanElectro-MaterialsSingaporePteLtd', 'DoosanElectro-MaterialsLuxembourgSarl', 'DoosanElectro-Materials(Changshu)Co.,Ltd', 'DoosanShanghaiChemicalMaterialsCo.,Ltd', 'CircuitFoilLuxembourg', 'DoosanHongkongLtd', 'DoosanDigitalInnovationAmericaLLC', 'DoosanDigitalInnovationChinaLLC', 'BobcatDomestic', 'DoosanElectro-Materials(ShenZhen)Limited', 'DoosanDigitalInnovationEuropeLimited', 'DoosanElectro-MaterialsAmerica,LLC', 'DoosanBobcatEMEAs.r.o', 'DoosanHeavyIndustriesVietnamCo.,Ltd', 'DoosanBobcatIndiaPrivateLtd', 'DoosanInfracoreNorthAmericaLLC', 'DoosanBobcatChileS.A', 'DoosanBobcatSingaporePte.Ltd', 'BobcatCorp', 'DoosanInternationalAustraliaPtyLtd', 'DoosanBobcatChinaCo.,Ltd', 'DoosanHeavyIndustriesJapanCorp', 'DoosanPowerSystemsIndiaPrivateLtd', 'DoosanLogisticsEuropeGmbH', 'SichuanKelun-DoosanBiotechnologyCompanyLimited', 'DoosanHeavyIndustriesVietnamHaiphong', 'DoosanEnergySolutionKft', 'DoosanCorporationEuropeKft', 'DoosanInfracoreJapanCorp', 'MiraeAssetSecurities(Vietnam)LLC', 'MiraeAssetFinanceCompany(Vietnam', 'MiraeAssetSecurities(HK)Limited', 'MiraeAssetSecurities(UK)Ltd', 'MiraeAssetGlobalInvestments(HongKong)Ltd', 'MiraeAssetGlobalInvestments(USA)INC', 'MiraeAssetGlobalETFsHodlignsLimited', 'AsianaStaffService,Inc', 'KUMHOHOLDINGS(H.K.)CO,.LTD', 'WEIHAIPOINTHOTEL&GOLFRESORT.CO.,LTD', '동삼현대한매고분', 'AUST-RAILIANSHOPPINGNETWORKPTYLTD', 'VTVHYUNDAIHomeShoppingCo.LTD', '한섬파리', 'HYUNDAILIVARTVINA', 'LIVARTCANADA', '현대휘상무역(상해)유한공사', 'HyundaiL&CCanadaInc', 'HyundaiL&C(Shanghai)Co.,LTD', 'HyundaiL&CUSA,LLC', 'HyundaiL&CEuropeGmbH', 'AmericanSurfacingMaterials,LLC', '한우공정기계(상해)유한공사', 'EVERDIGMHEMTLLC', 'EVERDIGMMONGOLIALLC', 'EVERDIGMAMERICAINC', 'KAKAOJAPANCorp', 'KakaoGamesEuropeB.V', 'PT.PATHMOBILEINDONESIA', 'DaumServiceCHINACo.,Ltd', 'PATHMOBILEINCPTE.LTD', 'KlaytnPte.Ltd', 'READYENTERTAINMENT(shanghai)CO.,LTD', 'TAESIKMAUMGOLFCo.,LTD', 'KAKAOIXJAPANCORP', 'KAKAOIXCHINA.,LTD', 'KAKAOIXUSA,INC', 'KAKAOIXUKLTD', 'KAKAOIXHKLTD', 'KIARACAPITALⅡPTE.LTD', 'KISVietnamSecuritiesCorporation', 'KoreaInvestment&SecuritiesAsia,Ltd', 'KIMInvestmentFunds', 'POSCONPSNiobiumLLC', 'EQPCooperatiefU.A', '교보생명자산운용(미국', 'HYOSUNGVIETNAMCO.,LTD', 'HYOSUNGUSAINC', 'HyosungT&DINDIAPvtLtd', 'HyosungSteelCord(Qingdao)Co.,Ltd', 'HyosungSpandex(Quzhou)Co.,Ltd', 'HyosungSpandex(GuangDong)Co.,Ltd', 'HyosungSpandex(Jiaxing)Co.,Ltd', 'HyosungSpandex(Zhuhai)Co.,Ltd', 'HyosungSingaporePTELtd', 'HyosungNEWMaterial&Hitech(Quzhou)Co.,Ltd', 'HyosungJapanCo.,Ltd', 'PT.HYOSUNGJAKARTA', 'HyosungIstanbulTEKSTILLTD.STI', 'HyosungInternationalTrade(Jiaxing)Co.,Ltd', 'HyosungInternational(HK)Ltd', 'HyosungEuropeSRL', 'HyosungDongNaiCo.,LTD', 'HyosungChemicals(Jiaxing)Co.,Ltd', 'HyosungChemicalFiber(Jiaxing)Co.,Ltd', 'HyosungBrasilIndustriaEComercioDeFibrasLtda', 'GSTAutomotiveSafetyROS.R.L', 'GSTGlobalGmbh', 'GSTSafetyTextilesROS.R.L', 'ZhangjiagangXiaoshaCoilServiceCo.,Ltd', 'HYOSUNGINDIAPvtLtd', 'HyosungHoldingsUSA,Inc', 'HyosungQuangNam.Ltd', 'NantongHyosungTransformerCo.,Ltd', 'HyosungVinaChemicalsCo.,Ltd', 'HICOAmericaSales&Tech', 'HyosungLuxembourgS.A', 'HyosungCorporationIndiaPrivateLimited', 'HuizhouGalaxiaDeviceElectronics.Co.,Ltd', 'QingdaoGalaxiaDeviceElectronics.Co.,Ltd', 'GalaxiaJapanCo.,Ltd', 'DONGGUANSHINWHAINTERTEKCORP', 'SHINWHAINTERTEK(SUZHOU)CO.,LTD', 'HyosungRUS', 'NautilusHyosungAmerica,Inc', 'HyosungFinancialSystems(Huizhou)Co.,LTD', 'PT.CahayaTechnologyUnggas', 'SINGGREENVINACOMPANYLIMITED', 'PanOcean(America)Inc', 'PanOceanJapanCorporation', 'PanOceanSingaporeBulkCarrierPte.Ltd', 'SunjinMyanmarCompanyLimited', 'SorinShanghaiCorporationLtd', 'KCS', 'KCK', 'KCB', 'KCG', 'KCQ', 'KCT', 'KCI', 'KCID', 'KCV', 'KCC(Hanoi', 'KCCPaint', 'Basildon', 'MomentivePerformanceMaterialsAsiaPacificPteLtd', 'MomentivePerformanceMaterialsGmbH', 'MomentivePerformanceMaterials(India)PrivateLimited', 'MomentivePerformanceMaterials(NanTong)CO.,LTD', 'MomentivePerformanceMaterials(Thailand)Ltd', 'MomentivePerformanceMaterialsHongKongLtd', 'MomentivePerformanceMaterialsJapanLLC', 'MPMSiliconesLLC', 'MomentivePerformanceMaterialsUSALLC', 'MomentivePerformanceMaterialsQuartzInc', '코오롱화이버', 'OCI(HongKong)Limited', 'OCIInternationalInc', 'OCI(Shanghai)InternationalTradingLtd', 'UNIDGLOBALPHILS.,Inc', 'OCIUNIDEuropeB.V', 'JIANGSUOCICHEMICALCo.,Ltd', 'eTECARABIALTD', 'eTECMalaysiaSdn.Bhd', '상해개랑가', 'OCIMSdn.Bhd', 'MaSteelOCIChemical', 'OCIVietnam', 'PhilkoPeroxide', 'PhilkoChemLogistics', 'TangshanOCIChemicalCo.,Ltd', 'OCIChinaCo.,Ltd', 'OCISOLARPOWERLLC', 'ShandongOCI', 'ShandongOCI-Jianyangcarbonblack', 'OCISolar(China)Co.,Ltd', '에스비에스international', '디비MetalUSAINC', '디비MetalEuropeGmbH', 'PostandTelecomunicationJointStockInsuranceCorporation', 'ATMediaInvestor,LLC', 'NEXONCo.,Ltd', 'NEXONAmerica,Inc', 'NEXONMInc', 'NEXON(Thailand)Co.,Ltd', 'NEXONTAIWANLIMITED', 'STOKKEAS', 'BigHugeGames,Inc', '에이치비탕정', 'DigiparkSingaporePTE.LTD', 'JamCity,Inc', 'JOYGAMEInteractiveServicesLtd', 'Netmarble(Beijing)Limited', 'Netmarble(Thailand)Co.,Ltd', 'NetmarbleEMEAFZLLC', 'NETMARBLEHONGKONGLIMITED', 'NetmarbleJapanInc', 'NetmarbleJoyBombInc', 'NetmarbleTurkeySanayiveTicaretA.S', 'NetmarbleUS,Inc', 'PTNETMARBLEGAMESINDONESIA', 'EURIGSs.r.o', 'IGSChina', 'IGS&CPhilippinesInc', '태광화섬(상숙)유한공사', 'StarKistCo', 'SCASA', 'TTP', 'DWGlobalInc', 'DongwonJapanCo.,Ltd', '동원식품(상해)유한공사', 'DongwonF&BVietnamCo.,Ltd', 'StarKistSamoaCo', 'GalapescaS.A', 'CAPSEN', 'KKT', 'TALOFA', 'MVP', '위해삼조유한공사', '상해동부', 'DU', 'DV', 'PT.SAMINDOUTAMAKALTIM', 'PT.TRASINDOMURNIPERKASA', 'TIANJINYUJIACHANGINTERNATIONALFORWARDING', 'SINOKORBULKPTE.LTD', 'IMMInvestmentGroupJapan', 'CrianzaAviationLtd', 'PetriniLtd', 'Petrini2Ltd', 'CNBVINACO.,LTD', '이미인(상해)화장품유한공사', 'PWEFCooperatiefU.A', '다우재팬', 'DELITOONSAS', 'DAOUSIGNVIETNAMCOMPANYLIMITED', '상해금호일려소료유한공사', '광동금호일려고분자재료유한공사', '남경금포금호화공유한공사', '강소금호양농화공유한공사', 'Aekyung(Ningbo)ChemicalCo.,Ltd', 'AEKYUNGHONGKONGCOMPANYLIMITED', 'AEKYUNG(SHANGHAI)INVESTMENT&TRADINGCO.,LTD', 'AKVINACO.,LTD', 'AEKYUNG(FOSHAN)PAINTCO.,LTD', 'AKCHEMTECHHANOICO.,Ltd', 'AEKYUNGCHEMTECHINDIAPRIVATELIMITED', 'AEKYUNGCHEMICAL(QINGDAO)CO.,LTD', 'Aekyung(Shanghai)TradeCo.,Ltd', 'PT.HanilIndonesia', '케이지Netsorkscis', '동부USA', '동부ThaiSteel', '동부Japan', 'SamyangEngineeringPlastics(Shanghai)Co.,Ltd', 'SamyangEPHungaryCo.,Ltd', 'SamyangEPvietnamLLC']

In [24]:
dfTrans19[dfTrans19['매입회사'] == '동삼현대한매고분']

,매출회사,매입회사,매출액,국내계열사계(매출액),해외계열사계(매출액),국내매출액,해외매출액,매출액총계,year2,year,grpname2,매출사상/비,매출사금융/비금융,매출액Val,매입사상/비,매입사금융/비금융,grpname,grpcode,매출회사id,매입회사id
8477,이에이치케이이앤에스,동삼현대한매고분,67.0,0.0,67.0,0.0,67.0,67.0,2019,2018,현대백화점,비상장,비금융,67.0,NaN,NaN,ehyundai,38035,2101603529,NaN

In [25]:
dfTrans19.loc[8477, '매입회사id'] = 2830000000

In [26]:
dfTrans19[dfTrans19['매입회사'] == '드림라인쏠라파워1호']

,매출회사,매입회사,매출액,국내계열사계(매출액),해외계열사계(매출액),국내매출액,해외매출액,매출액총계,year2,year,grpname2,매출사상/비,매출사금융/비금융,매출액Val,매입사상/비,매입사금융/비금융,grpname,grpcode,매출회사id,매입회사id
8883,드림라인,드림라인쏠라파워1호,2.0,763.0,NaN,4984.0,365.0,5349.0,2019,2018,한국투자금융,비상장,비금융,169316.0,NaN,NaN,kinv,2702504,818160,NaN
8884,드림라인,드림라인쏠라파워1호,9.0,763.0,NaN,4984.0,365.0,5349.0,2019,2018,한국투자금융,비상장,비금융,169316.0,NaN,NaN,kinv,2702504,818160,NaN
8888,드림마크원,드림라인쏠라파워1호,19.0,4019.0,NaN,7.0,20905.0,20912.0,2019,2018,한국투자금융,비상장,비금융,7120.0,NaN,NaN,kinv,2702504,1902101842,NaN

In [27]:
dfTrans19.loc[8883, '매입회사id'] = 1902403697
dfTrans19.loc[8884, '매입회사id'] = 1902403697
dfTrans19.loc[8888, '매입회사id'] = 1902403697

In [28]:
dfTrans19[dfTrans19['매입회사'] == '탱그램디자인연']

,매출회사,매입회사,매출액,국내계열사계(매출액),해외계열사계(매출액),국내매출액,해외매출액,매출액총계,year2,year,grpname2,매출사상/비,매출사금융/비금융,매출액Val,매입사상/비,매입사금융/비금융,grpname,grpcode,매출회사id,매입회사id
9894,카카오인베스트먼트,탱그램디자인연,5.0,28.0,NaN,28.0,NaN,NaN,2019,2018,카카오,비상장,비금융,28.0,NaN,NaN,kakao,36027,1902702361,NaN

In [29]:
dfTrans19.loc[9894, '매입회사id'] = 16028567

In [30]:
dfTrans19[dfTrans19['매입회사'] == '디비라이텍']

,매출회사,매입회사,매출액,국내계열사계(매출액),해외계열사계(매출액),국내매출액,해외매출액,매출액총계,year2,year,grpname2,매출사상/비,매출사금융/비금융,매출액Val,매입사상/비,매입사금융/비금융,grpname,grpcode,매출회사id,매입회사id
10890,디비아이엔씨,디비라이텍,285.0,46302.0,0.0,122170.0,84669.0,206839.0,2019,2018,DB,상장,비금융,206839.0,NaN,NaN,DB,365,352098,NaN
10913,디비메탈,디비라이텍,0.0,56028.0,94048.0,187555.0,324816.0,512371.0,2019,2018,DB,비상장,비금융,512372.0,NaN,NaN,DB,365,12097776,NaN
10936,디비월드,디비라이텍,0.0,1101.0,0.0,12140.0,0.0,12140.0,2019,2018,DB,비상장,비금융,12140.0,NaN,NaN,DB,365,910813,NaN
10959,디비하이텍,디비라이텍,0.0,0.0,0.0,134995.0,534284.0,669279.0,2019,2018,DB,상장,비금융,669279.0,NaN,NaN,DB,365,350354,NaN
10982,동부철,디비라이텍,0.0,0.0,0.0,0.0,0.0,0.0,2019,2018,DB,비상장,비금융,0.0,NaN,NaN,DB,365,65122,NaN
11005,디비스탁인베스트,디비라이텍,0.0,0.0,0.0,256.0,0.0,256.0,2019,2018,DB,비상장,비금융,256.0,NaN,NaN,DB,365,19071407,NaN
11028,디비에프아이에스,디비라이텍,0.0,47260.0,0.0,47269.0,0.0,47269.0,2019,2018,DB,비상장,비금융,47269.0,NaN,NaN,DB,365,24038019,NaN
11051,디비인베스트,디비라이텍,0.0,0.0,0.0,933.0,0.0,933.0,2019,2018,DB,비상장,비금융,933.0,NaN,NaN,DB,365,16003715,NaN
11074,디비저축은행,디비라이텍,0.0,79.0,0.0,75424.0,0.0,75424.0,2019,2018,DB,비상장,금융,75423.0,NaN,NaN,DB,365,881562,NaN
11097,디비금융서비스,디비라이텍,0.0,3675.0,0.0,13311.0,0.0,13311.0,2019,2018,DB,비상장,금융,13311.0,NaN,NaN,DB,365,23044292,NaN
11120,디비금융투자,디비라이텍,0.0,796.0,0.0,725156.0,0.0,725156.0,2019,2018,DB,상장,금융,725156.0,NaN,NaN,DB,365,821640,NaN
11143,디비생명보험,디비라이텍,4.0,4520.0,0.0,2180825.0,0.0,2180825.0,2019,2018,DB,비상장,금융,2180825.0,NaN,NaN,DB,365,821420,NaN
11166,디비손해보험,디비라이텍,56.0,29359.0,0.0,14868022.0,127051.0,14995073.0,2019,2018,DB,상장,금융,14995073.0,NaN,NaN,DB,365,870099,NaN
11189,디비씨앤에스자동차손해사정,디비라이텍,0.0,48587.0,0.0,49587.0,0.0,49587.0,2019,2018,DB,비상장,금융,49587.0,NaN,NaN,DB,365,18004172,NaN
11212,디비씨에스아이손해사정,디비라이텍,0.0,40322.0,0.0,40322.0,0.0,40322.0,2019,2018,DB,비상장,금융,40322.0,NaN,NaN,DB,365,18031282,NaN
11235,디비씨에이에스손해사정,디비라이텍,0.0,52212.0,0.0,52212.0,0.0,52212.0,2019,2018,DB,비상장,금융,52212.0,NaN,NaN,DB,365,18031283,NaN
11258,디비엠앤에스,디비라이텍,0.0,35179.0,0.0,35555.0,0.0,35555.0,2019,2018,DB,비상장,금융,35555.0,NaN,NaN,DB,365,19098370,NaN
11281,디비자동차보험손해사정,디비라이텍,0.0,85014.0,0.0,85014.0,0.0,85014.0,2019,2018,DB,비상장,금융,85014.0,NaN,NaN,DB,365,820466,NaN
11304,디비자산운용,디비라이텍,0.0,197.0,0.0,25525.0,0.0,25525.0,2019,2018,DB,비상장,금융,25525.0,NaN,NaN,DB,365,607142,NaN
11327,디비캐피탈,디비라이텍,0.0,667.0,0.0,15007.0,0.0,15007.0,2019,2018,DB,비상장,금융,15007.0,NaN,NaN,DB,365,56018,NaN

In [31]:
dfTrans19.loc[10890, '매입회사id'] = 137656
dfTrans19.loc[10913, '매입회사id'] = 137656
dfTrans19.loc[10936, '매입회사id'] = 137656
dfTrans19.loc[10959, '매입회사id'] = 137656
dfTrans19.loc[10982, '매입회사id'] = 137656
dfTrans19.loc[11005, '매입회사id'] = 137656
dfTrans19.loc[11028, '매입회사id'] = 137656
dfTrans19.loc[11051, '매입회사id'] = 137656
dfTrans19.loc[11074, '매입회사id'] = 137656
dfTrans19.loc[11097, '매입회사id'] = 137656
dfTrans19.loc[11120, '매입회사id'] = 137656
dfTrans19.loc[11143, '매입회사id'] = 137656
dfTrans19.loc[11166, '매입회사id'] = 137656
dfTrans19.loc[11189, '매입회사id'] = 137656
dfTrans19.loc[11212, '매입회사id'] = 137656
dfTrans19.loc[11235, '매입회사id'] = 137656
dfTrans19.loc[11258, '매입회사id'] = 137656
dfTrans19.loc[11281, '매입회사id'] = 137656
dfTrans19.loc[11304, '매입회사id'] = 137656
dfTrans19.loc[11327, '매입회사id'] = 137656

In [32]:
dfTrans19[dfTrans19['매입회사'] == '유진스타제2호사모투자']

,매출회사,매입회사,매출액,국내계열사계(매출액),해외계열사계(매출액),국내매출액,해외매출액,매출액총계,year2,year,grpname2,매출사상/비,매출사금융/비금융,매출액Val,매입사상/비,매입사금융/비금융,grpname,grpcode,매출회사id,매입회사id
12233,유진프라이빗에쿼티,유진스타제2호사모투자,513.0,3007.0,NaN,3282.0,NaN,NaN,2019,2018,유진,비상장,비금융,3282.0,NaN,NaN,eugenes,653,1302904046,NaN

In [33]:
dfTrans19.loc[12233, '매입회사id'] = 1803200394

In [8]:
dfTrans19[dfTrans19['매입회사'] == '디디아이에스와이230위탁관리부동산투자회사']

,매출회사,매입회사,매출액,국내계열사계(매출액),해외계열사계(매출액),국내매출액,해외매출액,매출액총계,year2,year,grpname2,매출사상/비,매출사금융/비금융,매출액Val,매입사상/비,매입사금융/비금융,grpname,grpcode,매출회사id,매입회사id
1664,디앤디인베스트먼트,디디아이에스와이230위탁관리부동산투자회사,1620.0,1620.0,NaN,1720.0,NaN,NaN,2019,2018,에스케이,비상장,비금융,1720.0,NaN,NaN,sk,535,1903700469,NaN

In [9]:
dfTrans19.loc[1664, '매입회사id'] = 2101809024

In [11]:
dfTrans19[dfTrans19['매입회사'] == '드림라인솔라파워5호']

,매출회사,매입회사,매출액,국내계열사계(매출액),해외계열사계(매출액),국내매출액,해외매출액,매출액총계,year2,year,grpname2,매출사상/비,매출사금융/비금융,매출액Val,매입사상/비,매입사금융/비금융,grpname,grpcode,매출회사id,매입회사id
5611,한화갤러리아타임월드,드림라인솔라파워5호,0.0,3446.0,0.0,332681.0,0.0,332681.0,2019,2018,한화,상장,비금융,332681.0,NaN,NaN,hanwha,913,620580,NaN
5753,한화에스테이트,드림라인솔라파워5호,0.0,86755.0,0.0,99950.0,NaN,NaN,2019,2018,한화,비상장,비금융,99950.0,NaN,NaN,hanwha,913,39667,NaN
5940,한화시스템,드림라인솔라파워5호,0.0,230785.0,4593.0,1095012.0,26404.0,1121416.0,2019,2018,한화,비상장,비금융,1121416.0,NaN,NaN,hanwha,913,128888,NaN

In [12]:
dfTrans19.loc[5611, '매입회사id'] = 1902902067
dfTrans19.loc[5753, '매입회사id'] = 386383
dfTrans19.loc[5940, '매입회사id'] = 386383

In [13]:
dfTrans19[dfTrans19['매입회사'] == '센트럴관광개발']

,매출회사,매입회사,매출액,국내계열사계(매출액),해외계열사계(매출액),국내매출액,해외매출액,매출액총계,year2,year,grpname2,매출사상/비,매출사금융/비금융,매출액Val,매입사상/비,매입사금융/비금융,grpname,grpcode,매출회사id,매입회사id
6632,신세계,센트럴관광개발,388.0,196180.0,NaN,1739327.0,NaN,NaN,2019,2018,신세계,상장,비금융,1739327.0,NaN,NaN,shinsegae,577,620084,NaN
6693,신세계센트럴시티,센트럴관광개발,2339.0,101977.0,NaN,142969.0,NaN,NaN,2019,2018,신세계,비상장,비금융,172538.0,NaN,NaN,shinsegae,577,711268,NaN
6718,까사미아,센트럴관광개발,2472.0,7115.0,NaN,109567.0,NaN,NaN,2019,2018,신세계,비상장,비금융,109567.0,NaN,NaN,shinsegae,577,274224,NaN
6778,신세계조선호텔,센트럴관광개발,93.0,14890.0,NaN,191684.0,NaN,NaN,2019,2018,신세계,비상장,비금융,191684.0,NaN,NaN,shinsegae,577,630306,NaN
6807,신세계푸드,센트럴관광개발,187.0,397221.0,NaN,1263417.0,268.0,1263685.0,2019,2018,신세계,상장,비금융,1263685.0,NaN,NaN,shinsegae,577,40807,NaN
6837,신세계엘앤비,센트럴관광개발,32.0,56681.0,NaN,93560.0,NaN,NaN,2019,2018,신세계,비상장,비금융,93560.0,NaN,NaN,shinsegae,577,13072689,NaN
6861,신세계건설,센트럴관광개발,94209.0,675215.0,229.0,1084040.0,229.0,1084269.0,2019,2018,신세계,상장,비금융,1084269.0,NaN,NaN,shinsegae,577,100960,NaN
6897,신세계영랑호리조트,센트럴관광개발,0.0,1581.0,NaN,8171.0,NaN,NaN,2019,2018,신세계,비상장,비금융,8171.0,NaN,NaN,shinsegae,577,494258,NaN
6951,신세계아이앤씨,센트럴관광개발,6547.0,286625.0,NaN,373529.0,2.0,373531.0,2019,2018,신세계,상장,비금융,373531.0,NaN,NaN,shinsegae,577,538787,NaN

In [15]:
dfTrans19.loc[6632, '매입회사id'] = 73540
dfTrans19.loc[6693, '매입회사id'] = 73540
dfTrans19.loc[6718, '매입회사id'] = 73540
dfTrans19.loc[6778, '매입회사id'] = 73540
dfTrans19.loc[6807, '매입회사id'] = 73540
dfTrans19.loc[6837, '매입회사id'] = 73540
dfTrans19.loc[6861, '매입회사id'] = 73540
dfTrans19.loc[6897, '매입회사id'] = 73540
dfTrans19.loc[6951, '매입회사id'] = 73540

In [16]:
dfTrans19[dfTrans19['매입회사'] == '케이티씨엔피그로쓰챔프2011의2호사모투자']

,매출회사,매입회사,매출액,국내계열사계(매출액),해외계열사계(매출액),국내매출액,해외매출액,매출액총계,year2,year,grpname2,매출사상/비,매출사금융/비금융,매출액Val,매입사상/비,매입사금융/비금융,grpname,grpcode,매출회사id,매입회사id
7908,네오플럭스,케이티씨엔피그로쓰챔프2011의2호사모투자,8425.0,10350.0,NaN,22219.0,NaN,NaN,2019,2018,두산,비상장,금융,22219.0,NaN,NaN,doosan,391,1903209021,NaN

In [17]:
dfTrans19.loc[7908, '매입회사id'] = 19066564

In [18]:
dfTrans19[dfTrans19['매입회사'] == 'PCA생명보험']

,매출회사,매입회사,매출액,국내계열사계(매출액),해외계열사계(매출액),국내매출액,해외매출액,매출액총계,year2,year,grpname2,매출사상/비,매출사금융/비금융,매출액Val,매입사상/비,매입사금융/비금융,grpname,grpcode,매출회사id,매입회사id
8335,미래에셋대우,PCA생명보험,231.0,18568.0,92.0,8999289.0,2278029.0,11277318.0,2019,2018,미래에셋,상장,금융,11277318.0,NaN,NaN,miraeasset,2602105,860085,NaN
8365,미래에셋자산운용,PCA생명보험,46.0,24066.0,179.0,265349.0,9176.0,274525.0,2019,2018,미래에셋,비상장,금융,274525.0,NaN,NaN,miraeasset,2602105,490050,NaN
8392,미래에셋컨설팅,PCA생명보험,10.0,4243.0,NaN,108786.0,NaN,NaN,2019,2018,미래에셋,비상장,비금융,108786.0,NaN,NaN,miraeasset,2602105,13045914,NaN

In [20]:
dfTrans19.loc[8335, '매입회사id'] = 821683
dfTrans19.loc[8365, '매입회사id'] = 821683
dfTrans19.loc[8392, '매입회사id'] = 821683

In [22]:
dfTrans19[dfTrans19['매입회사'] == '미래에셋파트너스5호']

,매출회사,매입회사,매출액,국내계열사계(매출액),해외계열사계(매출액),국내매출액,해외매출액,매출액총계,year2,year,grpname2,매출사상/비,매출사금융/비금융,매출액Val,매입사상/비,매입사금융/비금융,grpname,grpcode,매출회사id,매입회사id
8339,미래에셋대우,미래에셋파트너스5호,36.0,18568.0,92.0,8999289.0,2278029.0,11277318.0,2019,2018,미래에셋,상장,금융,11277318.0,NaN,NaN,miraeasset,2602105,860085,NaN

In [23]:
dfTrans19.loc[8339, '매입회사id'] = 13098472

In [34]:
idx = dfTrans19[dfTrans19['매입회사id'].isna()].index

In [35]:
dfTrans19.loc[idx, '매입회사id'] = 5350000000

In [38]:
dfUltown = pd.read_stata("../data/almeida/2019/out/almeida_own1_2019.dta")
dfUltown.head()

,year,year2,grpname2,grpname,grpcode,firmname,firmid,fid,ultown,avpos,sd,steps,loop,lastcontrol,central
0,2018.0,2019.0,애경,aekyung,615,우영운수,47919,1.0,1.000000,1.000000,1.0,NaN,0.0,100.0,0.000000
1,2018.0,2019.0,애경,aekyung,615,수원애경역사,73220,2.0,0.605655,3.206202,2.0,NaN,0.0,64.0,0.000000
2,2018.0,2019.0,애경,aekyung,615,애드미션,95760,3.0,0.852500,1.000000,1.0,NaN,0.0,85.0,0.000000
3,2018.0,2019.0,애경,aekyung,615,에이케이레저,99486,4.0,1.000000,2.569844,2.0,NaN,0.0,100.0,0.000000
4,2018.0,2019.0,애경,aekyung,615,에이케이에스앤디,125359,5.0,0.719310,2.206202,1.0,NaN,0.0,64.0,6.736839

In [39]:
dfUltown['매출회사 실질지분율'] = dfUltown['ultown']
dfUltown['매입회사 실질지분율'] = dfUltown['ultown']
dfUltown['매출회사id'] = dfUltown['firmid']
dfUltown['매입회사id'] = dfUltown['firmid']

In [41]:
dfUltown['매출회사id'].dtype

dtype('int32')

In [42]:
dfTrans19['매출회사id'].dtype

dtype('int64')

In [43]:
dfTrans19['매입회사id'].dtype

dtype('float64')

In [44]:
dfUltown['매입회사id'].dtype

dtype('int32')

In [45]:
dfTrans19['매입회사id'] = dfTrans19['매입회사id'].astype('int32')

In [46]:
dfTrans19Vr = dfTrans19.merge(dfUltown[['매출회사id', '매출회사 실질지분율']], on='매출회사id', how='left')\
                       .merge(dfUltown[['매입회사id', '매입회사 실질지분율']], on='매입회사id', how='left')
dfTrans19Vr.head()

,매출회사,매입회사,매출액,국내계열사계(매출액),해외계열사계(매출액),국내매출액,해외매출액,매출액총계,year2,year,...,매출사금융/비금융,매출액Val,매입사상/비,매입사금융/비금융,grpname,grpcode,매출회사id,매입회사id,매출회사 실질지분율,매입회사 실질지분율
0,삼성전자,삼성물산,78676.0,2269950.0,149436938.0,16821275.0,153560595.0,170381870.0,2019,2018,...,비금융,170381870.0,상장,비금융,samsung,511,380725,810053,0.08541,0.311626
1,삼성전자,삼성바이오에피스,1.0,2269950.0,149436938.0,16821275.0,153560595.0,170381870.0,2019,2018,...,비금융,170381870.0,비상장,비금융,samsung,511,380725,18082125,0.08541,0.081307
2,삼성전자,삼성디스플레이,164404.0,2269950.0,149436938.0,16821275.0,153560595.0,170381870.0,2019,2018,...,비금융,170381870.0,비상장,비금융,samsung,511,380725,18082126,0.08541,0.074901
3,삼성전자,세메스,5.0,2269950.0,149436938.0,16821275.0,153560595.0,170381870.0,2019,2018,...,비금융,170381870.0,비상장,비금융,samsung,511,380725,314528,0.08541,0.078187
4,삼성전자,삼성전자서비스,456109.0,2269950.0,149436938.0,16821275.0,153560595.0,170381870.0,2019,2018,...,비금융,170381870.0,비상장,비금융,samsung,511,380725,952133,0.08541,0.084836

In [48]:
dfTrans19.to_excel('../data/transactions-report/transactions2019.xlsx')

# 표4

In [6]:
lstNonChaebol = ['농협', '대우건설', '대우조선해양', '에쓰-오일', '케이티', '케이티앤지', 
                 '포스코', '한국지엠', '에이치엠엠', '한국항공우주산업', '쿠팡']
dfCmpnyNo = dfCmpnyNo[~dfCmpnyNo['기업집단명'].isin(lstNonChaebol)]
dfCmpnyNo

        기업집단명  동일인  계열사수    자산총액
0          DB  김준기    21   10366
1          DL  이준용    36   19627
2   IMM인베스트먼트  지성배    94    7895
3          SM  우오현    58   10450
4      교보생명보험  신창재    12   14413
5      금호석유화학  박찬구    15    6665
6      금호아시아나  박삼구    27   17442
7         네이버  이해진    45   13584
8          넥슨  김정주    18   11998
9         넷마블  방준혁    23   10703
11       다우키움  김익래    45    6593
12       대방건설  구교운    43    5326
15       동국제강  장세주    11    5956
16         동원  김재철    26    8458
17         두산  박정원    22   29659
18         롯데  신동빈    86  117781
19       미래에셋  박현주    38   19333
20      반도홀딩스  권홍사    28    5585
21         부영  이중근    23   23321
22         삼성  이재용    59  457305
23         삼양   김윤    11    5412
24        삼천리  이만득    42    7841
25         세아  이순형    29    9470
26       셀트리온  서정진     8   14855
27        신세계  이명희    45   46409
28        씨제이  이재현    79   34676
29     아모레퍼시픽  서경배    14    8009
30     아이에스지주  권혁운    46    5190
31         애경  장영신    37    5589
32       에스케이  최태원   148  239530
34      에이치디씨  정몽규    29   13549
36        엘에스  구자홍    58   25243
37         엘지  구광모    70  151322
38        엠디엠  문주현    22    5256
39         영풍  장형진    27   13170
40       오씨아이  이우현    18    9815
41         유진  유경선    52    5528
42        이랜드  박성수    33    9509
43       장금상선  정태순    19    6263
44         중앙  홍석현    56    5014
45       중흥건설  정창선    37    9207
46        지에스  허창수    80   67677
47        카카오  김범수   118   19952
48       케이씨씨  정몽진    18   12277
51        코오롱  이웅열    36   10299
53         태광  이호진    19    8767
54         태영  윤세영    63    9800
56         하림  김홍국    55   13044
57      하이트진로  박문덕    18    5448
59      한국타이어  조양래    21    9849
60     한국투자금융  김남구    30   14649
62         한라  정몽원    15    8104
63         한진  조원태    31   33600
64         한화  김승연    83   72898
65      현대백화점  정지선    25   18313
66      현대자동차  정의선    53  246084
67      현대중공업  정몽준    33   63803
68   현대해상화재보험  정몽윤    21    5322
69       호반건설  김상열    42   10698
70         효성  조현준    50   13281

In [7]:
len(dfCmpnyNo)

60

In [8]:
dfCmpnyNo['계열사수'].sum()

2421

In [9]:
dfTransactions.groupby(["grpname2", "매출회사id"])['매입회사'].nunique().mean()

8.859254878769958

In [10]:
dfTransactions.drop_duplicates('매출회사id')['국내계열사계'].mean()

110259.35903614458

In [11]:
dfTransactions.drop_duplicates('매출회사id')['국내계열사계'].sum() / dfTransactions.drop_duplicates('매출회사id')['매출액총계'].sum()

0.11768938604388808

In [12]:
dfTransactions.drop_duplicates('매출회사id')['국내계열사계'].sum() / dfTransactions.drop_duplicates('매출회사id')['국내매출액'].sum()

0.18964256709216387

In [13]:
dfTransactions.head()

,year,year2,grpname2,매출회사,매출회사id,매입회사,매입회사id,매출액,국내계열사계,해외계열사계,매출액총계,국내매출액,해외매출액
0,2020,2021,대방건설,대방건설,158856.0,대방하우징,21066402.0,153182.0,970711.0,NaN,1557457.0,1557457.0,NaN
1,2020,2021,대방건설,대방건설,158856.0,대방주택,21066401.0,103392.0,970711.0,NaN,1557457.0,1557457.0,NaN
2,2020,2021,대방건설,대방건설,158856.0,노블랜드,21066399.0,86208.0,970711.0,NaN,1557457.0,1557457.0,NaN
3,2020,2021,대방건설,대방건설,158856.0,디비건설,23007680.0,261352.0,970711.0,NaN,1557457.0,1557457.0,NaN
4,2020,2021,대방건설,대방건설,158856.0,디비산업개발,23007684.0,78658.0,970711.0,NaN,1557457.0,1557457.0,NaN

# 표 5

In [14]:
dfOV = pd.read_csv("../refactoring/data/overview/21소속회사개요utf-8.csv")
dfOV.head()

,법인등록번호,자산총액,직전사업결산일자,자본금액,자본총액,회사구분,부채총액,소속회사명,기업공개일,기업설립일,...,업종명,상시종업원수,공개년월,출력순위,대표자명,매출액,결산기일,당기순이익,기업집단명,rcmgCode
0,1.100000e+12,2.490000e+13,20210323.0,1.410000e+11,9.600000e+12,일반회사,1.530000e+13,롯데쇼핑,20060209.0,19700702,...,소매업; 자동차 제외,24963,202105,1444,강희태,8.710000e+12,20201231.0,-1.030000e+12,롯데,620068
1,1.100000e+12,1.190000e+13,20210326.0,4.040000e+11,4.420000e+12,일반회사,7.450000e+12,지에스건설,19810803.0,19691219,...,종합 건설업,6928,202105,2196,임병용,8.890000e+12,20201231.0,3.270000e+11,지에스,500143
2,1.100000e+12,6.240000e+11,20210331.0,1.685000e+10,3.520000e+11,일반회사,2.720000e+11,삼라,NaN,19690826,...,종합 건설업,12,202105,276,조유선,1.490000e+11,20201231.0,7.785100e+10,SM,500429
3,1.100000e+12,7.360000e+12,20200325.0,4.900000e+11,3.490000e+12,일반회사,3.870000e+12,한화,19760625.0,19521028,...,화학 물질 및 화학제품 제조업; 의약품 제외,5026,202105,1053,옥경석 외,4.000000e+12,20191231.0,1.290000e+11,한화,350893
4,1.100000e+12,1.630000e+12,20210326.0,1.838800e+10,7.540000e+11,일반회사,8.800000e+11,동원산업,19890307.0,19690416,...,어업,761,202105,1343,이명우,7.020000e+11,20201231.0,7.895000e+10,동원,100030

In [15]:
len(dfOV)

2612

In [16]:
dfOV['공개년월'].unique()

array([202105])

In [17]:
dfOV[dfOV['공개년월']==202105]['소속회사명']

0         롯데쇼핑
1        지에스건설
2           삼라
3           한화
4         동원산업
         ...
2607    디엠산업개발
2608      디엠건설
2609    선남대방씨씨
2610    엘리움하우징
2611    유진에이엠씨
Name: 소속회사명, Length: 2612, dtype: object

In [18]:
dfOV[(dfOV['공개년월']==202105) & (~dfOV['기업공개일'].isnull()) & (~dfOV['기업집단명'].isin(lstNonChaebol))]

,법인등록번호,자산총액,직전사업결산일자,자본금액,자본총액,회사구분,부채총액,소속회사명,기업공개일,기업설립일,...,업종명,상시종업원수,공개년월,출력순위,대표자명,매출액,결산기일,당기순이익,기업집단명,rcmgCode
0,1.100000e+12,2.490000e+13,20210323.0,1.410000e+11,9.600000e+12,일반회사,1.530000e+13,롯데쇼핑,20060209.0,19700702,...,소매업; 자동차 제외,24963,202105,1444,강희태,8.710000e+12,20201231.0,-1.030000e+12,롯데,620068
1,1.100000e+12,1.190000e+13,20210326.0,4.040000e+11,4.420000e+12,일반회사,7.450000e+12,지에스건설,19810803.0,19691219,...,종합 건설업,6928,202105,2196,임병용,8.890000e+12,20201231.0,3.270000e+11,지에스,500143
3,1.100000e+12,7.360000e+12,20200325.0,4.900000e+11,3.490000e+12,일반회사,3.870000e+12,한화,19760625.0,19521028,...,화학 물질 및 화학제품 제조업; 의약품 제외,5026,202105,1053,옥경석 외,4.000000e+12,20191231.0,1.290000e+11,한화,350893
4,1.100000e+12,1.630000e+12,20210326.0,1.838800e+10,7.540000e+11,일반회사,8.800000e+11,동원산업,19890307.0,19690416,...,어업,761,202105,1343,이명우,7.020000e+11,20201231.0,7.895000e+10,동원,100030
6,1.100000e+12,1.130000e+13,20210324.0,1.100000e+12,1.250000e+12,금융보험업,1.000000e+13,한화투자증권,19861125.0,19620719,...,금융 및 보험관련 서비스업,1125,202105,2494,권희백,2.710000e+12,20201231.0,6.261200e+10,한화,860026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2290,1.940000e+12,4.070000e+12,20210324.0,5.460000e+11,1.290000e+12,일반회사,2.780000e+12,현대로템,20131030.0,19990701,...,기타 운송장비 제조업,3443,202105,2530,이용배,2.680000e+12,20201231.0,3.703400e+10,현대자동차,119613
2333,2.000000e+12,7.840000e+11,20210323.0,8.000000e+09,6.980000e+11,일반회사,8.616000e+10,광주신세계,20020207.0,19950410,...,소매업; 자동차 제외,180,202105,35,이동훈,1.480000e+11,20201231.0,4.316000e+10,신세계,74370
2472,2.150000e+12,7.580000e+11,20210330.0,5.310500e+10,2.830000e+11,일반회사,4.750000e+11,하림,20110502.0,20110104,...,식료품 제조업,2382,202105,1006,"김홍국, 박길연, 윤석춘",8.700000e+11,20201231.0,6.400000e+09,하림,16091473
2479,2.150000e+12,7.900000e+11,20210329.0,8.184000e+09,5.130000e+11,일반회사,2.780000e+11,두산퓨얼셀,20191018.0,20191001,...,전기장비 제조업,393,202105,1359,유수경,4.620000e+11,20201231.0,1.419000e+10,두산,2103300606
2487,2.200000e+12,1.160000e+12,20200626.0,1.920000e+11,2.180000e+11,일반회사,9.380000e+11,제주항공,20151106.0,20050125,...,항공 운송업,3120,202105,742,김이배,3.740000e+11,20201231.0,-3.020000e+11,애경,368575

In [19]:
len(dfOV[(dfOV['공개년월']==202105) & (~dfOV['기업공개일'].isnull())])/len(dfOV[dfOV['공개년월']==202105])

0.10872894333843798

In [20]:
dfOV[(dfOV['공개년월']==202105) & (~dfOV['기업공개일'].isnull())]['rcmgCode']

0           620068
1           500143
3           350893
4           100030
6           860026
           ...
2290        119613
2333         74370
2472      16091473
2479    2103300606
2487        368575
Name: rcmgCode, Length: 284, dtype: int64

In [21]:
dfOV[(dfOV['공개년월']==202105) & (~dfOV['기업공개일'].isnull()) & (~dfOV['rcmgCode'].isnull())]

,법인등록번호,자산총액,직전사업결산일자,자본금액,자본총액,회사구분,부채총액,소속회사명,기업공개일,기업설립일,...,업종명,상시종업원수,공개년월,출력순위,대표자명,매출액,결산기일,당기순이익,기업집단명,rcmgCode
0,1.100000e+12,2.490000e+13,20210323.0,1.410000e+11,9.600000e+12,일반회사,1.530000e+13,롯데쇼핑,20060209.0,19700702,...,소매업; 자동차 제외,24963,202105,1444,강희태,8.710000e+12,20201231.0,-1.030000e+12,롯데,620068
1,1.100000e+12,1.190000e+13,20210326.0,4.040000e+11,4.420000e+12,일반회사,7.450000e+12,지에스건설,19810803.0,19691219,...,종합 건설업,6928,202105,2196,임병용,8.890000e+12,20201231.0,3.270000e+11,지에스,500143
3,1.100000e+12,7.360000e+12,20200325.0,4.900000e+11,3.490000e+12,일반회사,3.870000e+12,한화,19760625.0,19521028,...,화학 물질 및 화학제품 제조업; 의약품 제외,5026,202105,1053,옥경석 외,4.000000e+12,20191231.0,1.290000e+11,한화,350893
4,1.100000e+12,1.630000e+12,20210326.0,1.838800e+10,7.540000e+11,일반회사,8.800000e+11,동원산업,19890307.0,19690416,...,어업,761,202105,1343,이명우,7.020000e+11,20201231.0,7.895000e+10,동원,100030
6,1.100000e+12,1.130000e+13,20210324.0,1.100000e+12,1.250000e+12,금융보험업,1.000000e+13,한화투자증권,19861125.0,19620719,...,금융 및 보험관련 서비스업,1125,202105,2494,권희백,2.710000e+12,20201231.0,6.261200e+10,한화,860026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2290,1.940000e+12,4.070000e+12,20210324.0,5.460000e+11,1.290000e+12,일반회사,2.780000e+12,현대로템,20131030.0,19990701,...,기타 운송장비 제조업,3443,202105,2530,이용배,2.680000e+12,20201231.0,3.703400e+10,현대자동차,119613
2333,2.000000e+12,7.840000e+11,20210323.0,8.000000e+09,6.980000e+11,일반회사,8.616000e+10,광주신세계,20020207.0,19950410,...,소매업; 자동차 제외,180,202105,35,이동훈,1.480000e+11,20201231.0,4.316000e+10,신세계,74370
2472,2.150000e+12,7.580000e+11,20210330.0,5.310500e+10,2.830000e+11,일반회사,4.750000e+11,하림,20110502.0,20110104,...,식료품 제조업,2382,202105,1006,"김홍국, 박길연, 윤석춘",8.700000e+11,20201231.0,6.400000e+09,하림,16091473
2479,2.150000e+12,7.900000e+11,20210329.0,8.184000e+09,5.130000e+11,일반회사,2.780000e+11,두산퓨얼셀,20191018.0,20191001,...,전기장비 제조업,393,202105,1359,유수경,4.620000e+11,20201231.0,1.419000e+10,두산,2103300606
2487,2.200000e+12,1.160000e+12,20200626.0,1.920000e+11,2.180000e+11,일반회사,9.380000e+11,제주항공,20151106.0,20050125,...,항공 운송업,3120,202105,742,김이배,3.740000e+11,20201231.0,-3.020000e+11,애경,368575

In [22]:
lstPublic = list(dfOV[(dfOV['공개년월']==202105) & (~dfOV['기업공개일'].isnull())]['rcmgCode'])

In [23]:
dfTransactions['매출회사 상장 여부'] = dfTransactions.copy().apply(lambda row: 1 if row['매출회사id'] in lstPublic else 0, axis=1)

In [24]:
dfTransactions.head(50)

,year,year2,grpname2,매출회사,매출회사id,매입회사,매입회사id,매출액,국내계열사계,해외계열사계,매출액총계,국내매출액,해외매출액,매출회사 상장 여부
0,2020,2021,대방건설,대방건설,1.588560e+05,대방하우징,2.106640e+07,153182.0,970711.0,NaN,1557457.0,1557457.0,NaN,0
1,2020,2021,대방건설,대방건설,1.588560e+05,대방주택,2.106640e+07,103392.0,970711.0,NaN,1557457.0,1557457.0,NaN,0
2,2020,2021,대방건설,대방건설,1.588560e+05,노블랜드,2.106640e+07,86208.0,970711.0,NaN,1557457.0,1557457.0,NaN,0
3,2020,2021,대방건설,대방건설,1.588560e+05,디비건설,2.300768e+07,261352.0,970711.0,NaN,1557457.0,1557457.0,NaN,0
4,2020,2021,대방건설,대방건설,1.588560e+05,디비산업개발,2.300768e+07,78658.0,970711.0,NaN,1557457.0,1557457.0,NaN,0
5,2020,2021,대방건설,대방건설,1.588560e+05,대방이노베이션,2.300768e+07,2.0,970711.0,NaN,1557457.0,1557457.0,NaN,0
6,2020,2021,대방건설,대방건설,1.588560e+05,대방이엔씨,1.801609e+09,1.0,970711.0,NaN,1557457.0,1557457.0,NaN,0
7,2020,2021,대방건설,대방건설,1.588560e+05,대방개발기업,1.801609e+09,655.0,970711.0,NaN,1557457.0,1557457.0,NaN,0
8,2020,2021,대방건설,대방건설,1.588560e+05,디비개발,1.801609e+09,5.0,970711.0,NaN,1557457.0,1557457.0,NaN,0
9,2020,2021,대방건설,대방건설,1.588560e+05,엔비건설,1.802306e+09,73890.0,970711.0,NaN,1557457.0,1557457.0,NaN,0
10,2020,2021,대방건설,대방건설,1.588560e+05,디비종합건설,1.801609e+09,49110.0,970711.0,NaN,1557457.0,1557457.0,NaN,0
11,2020,2021,대방건설,대방건설,1.588560e+05,디비주택,1.801609e+09,31269.0,970711.0,NaN,1557457.0,1557457.0,NaN,0
12,2020,2021,대방건설,대방건설,1.588560e+05,대방일산디엠시티,1.802101e+09,39058.0,970711.0,NaN,1557457.0,1557457.0,NaN,0
13,2020,2021,대방건설,대방건설,1.588560e+05,대방덕은,1.803502e+09,54864.0,970711.0,NaN,1557457.0,1557457.0,NaN,0
14,2020,2021,대방건설,대방건설,1.588560e+05,디엠개발,1.902707e+09,36557.0,970711.0,NaN,1557457.0,1557457.0,NaN,0
15,2020,2021,대방건설,대방건설,1.588560e+05,대방산업개발,4.795070e+05,125.0,970711.0,NaN,1557457.0,1557457.0,NaN,0
16,2020,2021,대방건설,대방건설,1.588560e+05,대방산업개발동탄,1.803502e+09,2383.0,970711.0,NaN,1557457.0,1557457.0,NaN,0
17,2020,2021,대방건설,대방산업개발,4.795070e+05,대방건설,1.588560e+05,5833.0,61693.0,NaN,74660.0,74660.0,NaN,0
18,2020,2021,대방건설,대방산업개발,4.795070e+05,디엠개발,1.902707e+09,0.0,61693.0,NaN,74660.0,74660.0,NaN,0
19,2020,2021,대방건설,대방산업개발,4.795070e+05,대방산업개발동탄,1.803502e+09,45128.0,61693.0,NaN,74660.0,74660.0,NaN,0
20,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움,2.301508e+09,1984.0,61693.0,NaN,74660.0,74660.0,NaN,0
21,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움개발,2.301508e+09,1984.0,61693.0,NaN,74660.0,74660.0,NaN,0
22,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움건설,2.301508e+09,2886.0,61693.0,NaN,74660.0,74660.0,NaN,0
23,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,74660.0,74660.0,NaN,0
24,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주택개발,1.802710e+09,2886.0,61693.0,NaN,74660.0,74660.0,NaN,0
25,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방건설,1.588560e+05,1929.0,3063.0,NaN,8119.0,8119.0,NaN,0
26,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방하우징,2.106640e+07,20.0,3063.0,NaN,8119.0,8119.0,NaN,0
27,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방주택,2.106640e+07,411.0,3063.0,NaN,8119.0,8119.0,NaN,0
28,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,노블랜드,2.106640e+07,86.0,3063.0,NaN,8119.0,8119.0,NaN,0
29,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,디비건설,2.300768e+07,222.0,3063.0,NaN,8119.0,8119.0,NaN,0
30,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,디비종합건설,1.801609e+09,14.0,3063.0,NaN,8119.0,8119.0,NaN,0
31,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방덕은,1.803502e+09,2.0,3063.0,NaN,8119.0,8119.0,NaN,0
32,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,디엠개발,1.902707e+09,47.0,3063.0,NaN,8119.0,8119.0,NaN,0
33,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방산업개발,4.795070e+05,332.0,3063.0,NaN,8119.0,8119.0,NaN,0
34,2020,2021,대방건설,지유인터내셔날,1.301302e+09,대방건설,1.588560e+05,144.0,196.0,NaN,391.0,391.0,NaN,0
35,2020,2021,대방건설,지유인터내셔날,1.301302e+09,대방산업개발,4.795070e+05,52.0,196.0,NaN,391.0,391.0,NaN,0
36,2020,2021,대방건설,디비일산,1.801809e+09,대방일산디엠시티,1.802101e+09,10107.0,10107.0,NaN,10107.0,10107.0,NaN,0
37,2020,2021,대방건설,디케이일산,1.801809e+09,대방일산디엠시티,1.802101e+09,10107.0,10107.0,NaN,10107.0,10107.0,NaN,0
38,2020,2021,한진,대한항공,9.900270e+05,한진칼,2.108315e+07,1158.0,65681.0,318.0,7405006.0,736452.0,6668554.0,1
39,2020,2021,한진,대한항공,9.900270e+05,한진,7.101050e+05,709.0,65681.0,318.0,7405006.0,736452.0,6668554.0,1
40,2020,2021,한진,대한항공,9.900270e+05,진에어,1.300692e+07,56518.0,65681.0,318.0,7405006.0,736452.0,6668554.0,1
41,2020,2021,한진,대한항공,9.900270e+05,정석기업,8.116370e+05,141.0,65681.0,318.0,7405006.0,736452.0,6668554.0,1
42,2020,2021,한진,대한항공,9.900270e+05,칼호텔네트워크,1.687390e+05,265.0,65681.0,318.0,7405006.0,736452.0,6668554.0,1
43,2020,2021,한진,대한항공,9.900270e+05,토파스여행정보,1.059990e+05,187.0,65681.0,318.0,7405006.0,736452.0,6668554.0,1
44,2020,2021,한진,대한항공,9.900270e+05,한진관광,1.909195e+07,3489.0,65681.0,318.0,7405006.0,736452.0,6668554.0,1
45,2020,2021,한진,대한항공,9.900270e+05,한국공항,8.100610e+05,663.0,65681.0,318.0,7405006.0,736452.0,6668554.0,1
46,2020,2021,한진,대한항공,9.900270e+05,한진정보통신,8.138770e+05,1478.0,65681.0,318.0,7405006.0,736452.0,6668554.0,1
47,2020,2021,한진,대한항공,9.900270e+05,항공종합서비스,1.672550e+05,322.0,65681.0,318.0,7405006.0,736452.0,6668554.0,1
48,2020,2021,한진,대한항공,9.900270e+05,싸이버스카이,2.112800e+05,44.0,65681.0,318.0,7405006.0,736452.0,6668554.0,1
49,2020,2021,한진,대한항공,9.900270e+05,한국글로발로지스틱스시스템,1.275860e+05,142.0,65681.0,318.0,7405006.0,736452.0,6668554.0,1

In [25]:
dfTransactions[dfTransactions['매출회사 상장 여부'] == 1].groupby(["grpname2", "매출회사id"])['매입회사'].nunique().mean()

18.731060606060606

In [26]:
dfTransactions[dfTransactions['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id')['국내계열사계'].mean()

335199.1477272727

In [27]:
284/2612

0.10872894333843798

In [28]:
dfTransactions[dfTransactions['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id')['국내계열사계'].sum() / \
dfTransactions[dfTransactions['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id')['매출액총계'].sum()

0.08125688137676765

In [29]:
dfTransactions[dfTransactions['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id')['국내계열사계'].sum() / \
dfTransactions[dfTransactions['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id')['국내매출액'].sum()

0.1423811195045182

# 표 6

In [30]:
2612 - 284

2328

In [31]:
_ / 2612

0.891271056661562

In [32]:
len(dfOV[(dfOV['공개년월']==202105) & (~dfOV['기업공개일'].isnull()) & (~dfOV['기업집단명'].isin(lstNonChaebol))])

258

In [33]:
dfCmpnyNo['계열사수'].sum() - len(dfOV[(dfOV['공개년월']==202105) & (~dfOV['기업공개일'].isnull()) & (~dfOV['기업집단명'].isin(lstNonChaebol))])

2163

In [34]:
_ / dfCmpnyNo['계열사수'].sum()

0.8934324659231723

In [35]:
print(dfTransactions[dfTransactions['매출회사 상장 여부'] == 0].groupby(["grpname2", "매출회사id"])['매입회사'].nunique().mean())
print(dfTransactions[dfTransactions['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id')['국내계열사계'].mean())
print(dfTransactions[dfTransactions['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id')['국내계열사계'].sum() / \
dfTransactions[dfTransactions['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id')['매출액총계'].sum())
print(dfTransactions[dfTransactions['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id')['국내계열사계'].sum() / \
dfTransactions[dfTransactions['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id')['국내매출액'].sum())

7.032936229852838
67720.60243553009
0.2028046292753209
0.2751273984611473

# 표 7

In [36]:
dfCmpnyNo['자산총액'] = dfCmpnyNo['자산총액'].copy().replace(',', '', regex=True)

In [37]:
dfCmpnyNo['자산총액'] = dfCmpnyNo['자산총액'].astype(float)

In [38]:
dfCmpnyNo['재벌 자산 순위'] = dfCmpnyNo['자산총액'].copy().rank(ascending=False)

In [39]:
dfCmpnyNo.head()

       기업집단명  동일인  계열사수     자산총액  재벌 자산 순위
0         DB  김준기    21  10366.0      33.0
1         DL  이준용    36  19627.0      16.0
2  IMM인베스트먼트  지성배    94   7895.0      45.0
3         SM  우오현    58  10450.0      32.0
4     교보생명보험  신창재    12  14413.0      22.0

In [40]:
# dfTransactions['grpname2'] = dfTransactions['grpname2'].copy().replace('DL', '대림', regex=True)
dfTransactions['grpname2'] = dfTransactions['grpname2'].copy().replace('대림', 'DL', regex=True)
dfTransactionsRank = dfTransactions.merge(dfCmpnyNo, how='left', left_on='grpname2', right_on='기업집단명')
dfTransactionsRank.head()

,year,year2,grpname2,매출회사,매출회사id,매입회사,매입회사id,매출액,국내계열사계,해외계열사계,매출액총계,국내매출액,해외매출액,매출회사 상장 여부,기업집단명,동일인,계열사수,자산총액,재벌 자산 순위
0,2020,2021,대방건설,대방건설,158856.0,대방하우징,21066402.0,153182.0,970711.0,NaN,1557457.0,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0
1,2020,2021,대방건설,대방건설,158856.0,대방주택,21066401.0,103392.0,970711.0,NaN,1557457.0,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0
2,2020,2021,대방건설,대방건설,158856.0,노블랜드,21066399.0,86208.0,970711.0,NaN,1557457.0,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0
3,2020,2021,대방건설,대방건설,158856.0,디비건설,23007680.0,261352.0,970711.0,NaN,1557457.0,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0
4,2020,2021,대방건설,대방건설,158856.0,디비산업개발,23007684.0,78658.0,970711.0,NaN,1557457.0,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0

In [41]:
dfTransactionsRank[dfTransactionsRank['재벌 자산 순위'].isna()]['grpname2'].unique()

array(['한국지엠', '대우건설', '대우조선해양', '에쓰-오일', '한국항공우주산업', '농협', '케이티앤지', '쿠팡',
       '케이티', '에이치엠엠', '포스코'], dtype=object)

In [42]:
dfTransactionsRank = dfTransactionsRank[~dfTransactionsRank['재벌 자산 순위'].isna()]

In [43]:
dfTR10 = dfTransactionsRank[dfTransactionsRank['재벌 자산 순위'] <= 10]
dfTR10['grpname2'].unique()

array(['현대중공업', '롯데', '에스케이', '신세계', '삼성', '엘지', '현대자동차', '씨제이', '한화',
       '지에스'], dtype=object)

In [44]:
print(dfCmpnyNo[dfCmpnyNo['재벌 자산 순위'] <= 10]['계열사수'].sum())
print(dfCmpnyNo['계열사수'].sum())
print(dfCmpnyNo[dfCmpnyNo['재벌 자산 순위'] <= 10]['계열사수'].sum() / dfCmpnyNo['계열사수'].sum())
print(dfTR10.groupby(["매출회사id"])['매입회사'].nunique().mean())
print(dfTR10.drop_duplicates('매출회사id')['국내계열사계'].mean())
print(dfTR10.drop_duplicates('매출회사id')['국내계열사계'].sum() / \
dfTR10.drop_duplicates('매출회사id')['매출액총계'].sum())
print(dfTR10.drop_duplicates('매출회사id')['국내계열사계'].sum() / \
dfTR10.drop_duplicates('매출회사id')['국내매출액'].sum())

736
2421
0.30400660883932257
12.56021897810219
247103.43144424132
0.1318299251396386
0.2425110067169063

In [45]:
len(dfCmpnyNo)

60

In [46]:
dfTransactionsRank['grpname2'].nunique()

60

In [47]:
dfTransactions['grpname2'].nunique()

71

In [48]:
dfOV[(~dfOV['기업집단명'].isin(lstNonChaebol)) & (dfOV['공개년월']==202105)]['기업집단명'].nunique()

60

In [49]:
lstR10 = ['현대중공업', '롯데', '에스케이', '신세계', '삼성', '엘지', '현대자동차', '씨제이', '한화', '지에스']

In [50]:
len(dfOV[(dfOV['기업집단명'].isin(lstR10)) & (dfOV['공개년월']==202105) & (~dfOV['기업공개일'].isnull())])

105

# 표 8

In [51]:
print(len(dfOV[(dfOV['기업집단명'].isin(lstR10)) & (dfOV['공개년월']==202105) & (~dfOV['기업공개일'].isnull())]))
print(len(dfOV[(dfOV['기업집단명'].isin(lstR10)) & (dfOV['공개년월']==202105) & (~dfOV['기업공개일'].isnull())]) \
      / len(dfOV[(dfOV['기업집단명'].isin(lstR10)) & (dfOV['공개년월']==202105)]))
print(dfTR10[dfTR10['매출회사 상장 여부'] == 1].groupby(["매출회사id"])['매입회사'].nunique().mean())
print(dfTR10[dfTR10['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id')['국내계열사계'].mean())
print(dfTR10[dfTR10['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id')['국내계열사계'].sum() / \
dfTR10[dfTR10['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id')['매출액총계'].sum())
print(dfTR10[dfTR10['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id')['국내계열사계'].sum() / \
dfTR10[dfTR10['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id')['국내매출액'].sum())

105
0.14266304347826086
28.57843137254902
669017.1372549019
0.08991111955238748
0.17340552044103388

In [52]:
105/736

0.14266304347826086

# 표 9

In [53]:
print(len(dfOV[(dfOV['기업집단명'].isin(lstR10)) & (dfOV['공개년월']==202105) & (dfOV['기업공개일'].isnull())]))
print(len(dfOV[(dfOV['기업집단명'].isin(lstR10)) & (dfOV['공개년월']==202105) & (dfOV['기업공개일'].isnull())]) \
      / len(dfOV[(dfOV['기업집단명'].isin(lstR10)) & (dfOV['공개년월']==202105)]))
print(dfTR10[dfTR10['매출회사 상장 여부'] == 0].groupby(["매출회사id"])['매입회사'].nunique().mean())
print(dfTR10[dfTR10['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id')['국내계열사계'].mean())
print(dfTR10[dfTR10['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id')['국내계열사계'].sum() / \
dfTR10[dfTR10['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id')['매출액총계'].sum())
print(dfTR10[dfTR10['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id')['국내계열사계'].sum() / \
dfTR10[dfTR10['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id')['국내매출액'].sum())

631
0.8573369565217391
8.896860986547086
150395.1213483146
0.25128558157413483
0.4085038840593114

# 표 10

In [54]:
dfTR5 = dfTransactionsRank[dfTransactionsRank['재벌 자산 순위'] <= 5]
dfTR5['grpname2'].unique()

array(['롯데', '에스케이', '삼성', '엘지', '현대자동차'], dtype=object)

In [55]:
lstR5 = list(dfTR5['grpname2'].unique())
lstR5

['롯데', '에스케이', '삼성', '엘지', '현대자동차']

In [56]:
print(dfCmpnyNo[dfCmpnyNo['재벌 자산 순위'] <= 5]['계열사수'].sum())
print(dfCmpnyNo['계열사수'].sum())
print(dfCmpnyNo[dfCmpnyNo['재벌 자산 순위'] <= 5]['계열사수'].sum() / dfCmpnyNo['계열사수'].sum())
print(dfTR5.groupby(["매출회사id"])['매입회사'].nunique().mean())
print(dfTR5.drop_duplicates('매출회사id')['국내계열사계'].mean())
print(dfTR5.drop_duplicates('매출회사id')['국내계열사계'].sum() / \
dfTR5.drop_duplicates('매출회사id')['매출액총계'].sum())
print(dfTR5.drop_duplicates('매출회사id')['국내계열사계'].sum() / \
dfTR5.drop_duplicates('매출회사id')['국내매출액'].sum())

416
2421
0.1718298223874432
14.758409785932722
354909.00306748465
0.13932457965835815
0.2764774487329435

# 표 11

In [57]:
print(len(dfOV[(dfOV['기업집단명'].isin(lstR5)) & (dfOV['공개년월']==202105) & (~dfOV['기업공개일'].isnull())]))
print(len(dfOV[(dfOV['기업집단명'].isin(lstR5)) & (dfOV['공개년월']==202105) & (~dfOV['기업공개일'].isnull())])\
      / len(dfOV[(dfOV['기업집단명'].isin(lstR5)) & (dfOV['공개년월']==202105)]))
print(dfTR5[dfTR5['매출회사 상장 여부'] == 1].groupby(["매출회사id"])['매입회사'].nunique().mean())
print(dfTR5[dfTR5['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id')['국내계열사계'].mean())
print(dfTR5[dfTR5['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id')['국내계열사계'].sum() / \
dfTR5[dfTR5['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id')['매출액총계'].sum())
print(dfTR5[dfTR5['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id')['국내계열사계'].sum() / \
dfTR5[dfTR5['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id')['국내매출액'].sum())

70
0.16826923076923078
30.82089552238806
908198.0746268657
0.09338466925312201
0.20228254972905133

# 표 12

In [58]:
print(len(dfOV[(dfOV['기업집단명'].isin(lstR5)) & (dfOV['공개년월']==202105) & (dfOV['기업공개일'].isnull())]))
print(len(dfOV[(dfOV['기업집단명'].isin(lstR5)) & (dfOV['공개년월']==202105) & (dfOV['기업공개일'].isnull())]) \
      / len(dfOV[(dfOV['기업집단명'].isin(lstR5)) & (dfOV['공개년월']==202105)]))
print(dfTR5[dfTR5['매출회사 상장 여부'] == 0].groupby(["매출회사id"])['매입회사'].nunique().mean())
print(dfTR5[dfTR5['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id')['국내계열사계'].mean())
print(dfTR5[dfTR5['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id')['국내계열사계'].sum() / \
dfTR5[dfTR5['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id')['매출액총계'].sum())
print(dfTR5[dfTR5['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id')['국내계열사계'].sum() / \
dfTR5[dfTR5['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id')['국내매출액'].sum())

346
0.8317307692307693
10.61923076923077
211780.16988416988
0.30670591964044763
0.4661552684211895

# 실질지분율

In [59]:
pwd

'/Users/choidamian/2021소유지배구조및내부거래현황보고서/notebook'

In [60]:
dfOwn2 = pd.read_excel('../refactoring/data/own-tables/data.xlsx').drop(columns=['Unnamed: 0'])
dfOwn2.head()

,firmid,fid,ultown,avpos,sd,steps,loop,lastcontrol,central,grpname2,소유지배구조 유형,vr,fam1,affil,wedge1,wedge2
0,5086.0,1,0.004698,4.692523,3.0,2.0,1.0,35,3.599998,유진,순환출자,0.359533,0.0,0.35932,0.345302,0.354836
1,102640.0,2,0.111364,3.460547,3.0,NaN,0.0,35,0.739998,유진,순환출자,1.000000,0.0,1.00000,0.238636,0.888636
2,165401.0,3,0.392760,2.213284,2.0,NaN,0.0,38,1.520000,유진,순환출자,1.000000,0.0,1.00000,-0.012760,0.607240
3,166364.0,4,1.000000,1.000000,1.0,NaN,0.0,100,1.200001,유진,순환출자,1.000000,1.0,0.00000,0.000000,0.000000
4,202487.0,5,0.135900,3.219830,2.0,NaN,0.0,35,0.000000,유진,순환출자,1.000000,0.0,1.00000,0.214100,0.864100

In [61]:
dfOwn2['grpname2'].unique()

array(['유진', '씨제이', 'DB', '아모레퍼시픽', '한화', '부영', '롯데', 'SM', '두산', '에이치디씨',
       '동국제강', '태영', '아이에스지주', '다우키움', '현대자동차', '이랜드', '현대해상화재보험',
       '금호석유화학', '지에스', '반도홀딩스', '엠디엠', '네이버', '삼양', '한진', '셀트리온', '동원',
       '하이트진로', '에스케이', '넥슨', '미래에셋', '태광', '애경', 'DL', '삼성', '오씨아이',
       '케이씨씨', '효성', '신세계', '대방건설', '중앙', '카카오', '현대백화점', '장금상선',
       '교보생명보험', 'IMM인베스트먼트', '현대중공업', '코오롱', '세아', '한국타이어', '넷마블', '영풍',
       '한국투자금융', '엘에스', '삼천리', '중흥건설', '금호아시아나', '한라', '하림', '엘지', '호반건설'],
      dtype=object)

In [62]:
dfVr = dfOwn2[['firmid', 'ultown']]
dfVr.head()

     firmid    ultown
0    5086.0  0.004698
1  102640.0  0.111364
2  165401.0  0.392760
3  166364.0  1.000000
4  202487.0  0.135900

In [63]:
print(len(dfVr))
print(len(dfVr[(dfVr['ultown'] < 0.2) & (dfVr['ultown'] >= 0)]))
print(len(dfVr[(dfVr['ultown'] < 0.3) & (dfVr['ultown'] >= 0.2)]))
print(len(dfVr[0.3 <=dfVr['ultown']]))

2399
1173
325
883

In [64]:
dfTransactionsRank.head()

,year,year2,grpname2,매출회사,매출회사id,매입회사,매입회사id,매출액,국내계열사계,해외계열사계,매출액총계,국내매출액,해외매출액,매출회사 상장 여부,기업집단명,동일인,계열사수,자산총액,재벌 자산 순위
0,2020,2021,대방건설,대방건설,158856.0,대방하우징,21066402.0,153182.0,970711.0,NaN,1557457.0,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0
1,2020,2021,대방건설,대방건설,158856.0,대방주택,21066401.0,103392.0,970711.0,NaN,1557457.0,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0
2,2020,2021,대방건설,대방건설,158856.0,노블랜드,21066399.0,86208.0,970711.0,NaN,1557457.0,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0
3,2020,2021,대방건설,대방건설,158856.0,디비건설,23007680.0,261352.0,970711.0,NaN,1557457.0,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0
4,2020,2021,대방건설,대방건설,158856.0,디비산업개발,23007684.0,78658.0,970711.0,NaN,1557457.0,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0

In [65]:
dfTransactionsRankVr = dfTransactionsRank.merge(dfVr, how='left', left_on='매출회사id', right_on='firmid')
dfTransactionsRankVr.head(50)

,year,year2,grpname2,매출회사,매출회사id,매입회사,매입회사id,매출액,국내계열사계,해외계열사계,...,국내매출액,해외매출액,매출회사 상장 여부,기업집단명,동일인,계열사수,자산총액,재벌 자산 순위,firmid,ultown
0,2020,2021,대방건설,대방건설,1.588560e+05,대방하우징,2.106640e+07,153182.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.588560e+05,1.000000
1,2020,2021,대방건설,대방건설,1.588560e+05,대방주택,2.106640e+07,103392.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.588560e+05,1.000000
2,2020,2021,대방건설,대방건설,1.588560e+05,노블랜드,2.106640e+07,86208.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.588560e+05,1.000000
3,2020,2021,대방건설,대방건설,1.588560e+05,디비건설,2.300768e+07,261352.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.588560e+05,1.000000
4,2020,2021,대방건설,대방건설,1.588560e+05,디비산업개발,2.300768e+07,78658.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.588560e+05,1.000000
5,2020,2021,대방건설,대방건설,1.588560e+05,대방이노베이션,2.300768e+07,2.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.588560e+05,1.000000
6,2020,2021,대방건설,대방건설,1.588560e+05,대방이엔씨,1.801609e+09,1.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.588560e+05,1.000000
7,2020,2021,대방건설,대방건설,1.588560e+05,대방개발기업,1.801609e+09,655.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.588560e+05,1.000000
8,2020,2021,대방건설,대방건설,1.588560e+05,디비개발,1.801609e+09,5.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.588560e+05,1.000000
9,2020,2021,대방건설,대방건설,1.588560e+05,엔비건설,1.802306e+09,73890.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.588560e+05,1.000000
10,2020,2021,대방건설,대방건설,1.588560e+05,디비종합건설,1.801609e+09,49110.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.588560e+05,1.000000
11,2020,2021,대방건설,대방건설,1.588560e+05,디비주택,1.801609e+09,31269.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.588560e+05,1.000000
12,2020,2021,대방건설,대방건설,1.588560e+05,대방일산디엠시티,1.802101e+09,39058.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.588560e+05,1.000000
13,2020,2021,대방건설,대방건설,1.588560e+05,대방덕은,1.803502e+09,54864.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.588560e+05,1.000000
14,2020,2021,대방건설,대방건설,1.588560e+05,디엠개발,1.902707e+09,36557.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.588560e+05,1.000000
15,2020,2021,대방건설,대방건설,1.588560e+05,대방산업개발,4.795070e+05,125.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.588560e+05,1.000000
16,2020,2021,대방건설,대방건설,1.588560e+05,대방산업개발동탄,1.803502e+09,2383.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.588560e+05,1.000000
17,2020,2021,대방건설,대방산업개발,4.795070e+05,대방건설,1.588560e+05,5833.0,61693.0,NaN,...,74660.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,4.795070e+05,1.000000
18,2020,2021,대방건설,대방산업개발,4.795070e+05,디엠개발,1.902707e+09,0.0,61693.0,NaN,...,74660.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,4.795070e+05,1.000000
19,2020,2021,대방건설,대방산업개발,4.795070e+05,대방산업개발동탄,1.803502e+09,45128.0,61693.0,NaN,...,74660.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,4.795070e+05,1.000000
20,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움,2.301508e+09,1984.0,61693.0,NaN,...,74660.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,4.795070e+05,1.000000
21,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움개발,2.301508e+09,1984.0,61693.0,NaN,...,74660.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,4.795070e+05,1.000000
22,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움건설,2.301508e+09,2886.0,61693.0,NaN,...,74660.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,4.795070e+05,1.000000
23,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,74660.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,4.795070e+05,1.000000
24,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주택개발,1.802710e+09,2886.0,61693.0,NaN,...,74660.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,4.795070e+05,1.000000
25,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방건설,1.588560e+05,1929.0,3063.0,NaN,...,8119.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.801707e+09,1.000000
26,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방하우징,2.106640e+07,20.0,3063.0,NaN,...,8119.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.801707e+09,1.000000
27,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방주택,2.106640e+07,411.0,3063.0,NaN,...,8119.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.801707e+09,1.000000
28,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,노블랜드,2.106640e+07,86.0,3063.0,NaN,...,8119.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.801707e+09,1.000000
29,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,디비건설,2.300768e+07,222.0,3063.0,NaN,...,8119.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.801707e+09,1.000000
30,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,디비종합건설,1.801609e+09,14.0,3063.0,NaN,...,8119.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.801707e+09,1.000000
31,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방덕은,1.803502e+09,2.0,3063.0,NaN,...,8119.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.801707e+09,1.000000
32,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,디엠개발,1.902707e+09,47.0,3063.0,NaN,...,8119.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.801707e+09,1.000000
33,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방산업개발,4.795070e+05,332.0,3063.0,NaN,...,8119.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.801707e+09,1.000000
34,2020,2021,대방건설,지유인터내셔날,1.301302e+09,대방건설,1.588560e+05,144.0,196.0,NaN,...,391.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.301302e+09,1.000000
35,2020,2021,대방건설,지유인터내셔날,1.301302e+09,대방산업개발,4.795070e+05,52.0,196.0,NaN,...,391.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.301302e+09,1.000000
36,2020,2021,대방건설,디비일산,1.801809e+09,대방일산디엠시티,1.802101e+09,10107.0,10107.0,NaN,...,10107.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.801809e+09,0.000000
37,2020,2021,대방건설,디케이일산,1.801809e+09,대방일산디엠시티,1.802101e+09,10107.0,10107.0,NaN,...,10107.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.801809e+09,0.000000
38,2020,2021,한진,대한항공,9.900270e+05,한진칼,2.108315e+07,1158.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,9.900270e+05,0.061883
39,2020,2021,한진,대한항공,9.900270e+05,한진,7.101050e+05,709.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,9.900270e+05,0.061883
40,2020,2021,한진,대한항공,9.900270e+05,진에어,1.300692e+07,56518.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,9.900270e+05,0.061883
41,2020,2021,한진,대한항공,9.900270e+05,정석기업,8.116370e+05,141.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,9.900270e+05,0.061883
42,2020,2021,한진,대한항공,9.900270e+05,칼호텔네트워크,1.687390e+05,265.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,9.900270e+05,0.061883
43,2020,2021,한진,대한항공,9.900270e+05,토파스여행정보,1.059990e+05,187.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,9.900270e+05,0.061883
44,2020,2021,한진,대한항공,9.900270e+05,한진관광,1.909195e+07,3489.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,9.900270e+05,0.061883
45,2020,2021,한진,대한항공,9.900270e+05,한국공항,8.100610e+05,663.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,9.900270e+05,0.061883
46,2020,2021,한진,대한항공,9.900270e+05,한진정보통신,8.138770e+05,1478.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,9.900270e+05,0.061883
47,2020,2021,한진,대한항공,9.900270e+05,항공종합서비스,1.672550e+05,322.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,9.900270e+05,0.061883
48,2020,2021,한진,대한항공,9.900270e+05,싸이버스카이,2.112800e+05,44.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,9.900270e+05,0.061883
49,2020,2021,한진,대한항공,9.900270e+05,한국글로발로지스틱스시스템,1.275860e+05,142.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,9.900270e+05,0.061883

In [66]:
dfTransactionsRankVr.tail(50)

,year,year2,grpname2,매출회사,매출회사id,매입회사,매입회사id,매출액,국내계열사계,해외계열사계,...,국내매출액,해외매출액,매출회사 상장 여부,기업집단명,동일인,계열사수,자산총액,재벌 자산 순위,firmid,ultown
15160,2020,2021,지에스,승산,7.901250e+05,지에스칼텍스,3.527050e+05,332.0,1020.0,NaN,...,24517.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,7.901250e+05,1.000000
15161,2020,2021,지에스,승산,7.901250e+05,지에스리테일,8.100450e+05,165.0,1020.0,NaN,...,24517.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,7.901250e+05,1.000000
15162,2020,2021,지에스,승산,7.901250e+05,지에스홈쇼핑,2.370700e+04,471.0,1020.0,NaN,...,24517.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,7.901250e+05,1.000000
15163,2020,2021,지에스,승산,7.901250e+05,지에스건설,5.001430e+05,15.0,1020.0,NaN,...,24517.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,7.901250e+05,1.000000
15164,2020,2021,지에스,승산,7.901250e+05,지에스네오텍,5.020650e+05,12.0,1020.0,NaN,...,24517.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,7.901250e+05,1.000000
15165,2020,2021,지에스,승산,7.901250e+05,삼양인터내셔날,6.135330e+05,12.0,1020.0,NaN,...,24517.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,7.901250e+05,1.000000
15166,2020,2021,지에스,승산,7.901250e+05,지에스아이티엠,NaN,12.0,1020.0,NaN,...,24517.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,7.901250e+05,1.000000
15167,2020,2021,지에스,승산,7.901250e+05,가승개발,1.802408e+09,1.0,1020.0,NaN,...,24517.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,7.901250e+05,1.000000
15168,2020,2021,지에스,승산,7.901250e+05,가승개발,1.802408e+09,1.0,1020.0,NaN,...,24517.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,7.901250e+05,1.000000
15169,2020,2021,지에스,삼정건업,1.906926e+07,삼양통상,3.205100e+05,425.0,425.0,NaN,...,8976.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,1.906926e+07,0.875000
15170,2020,2021,지에스,지에스이앤알,1.947210e+05,지에스엠비즈,2.982400e+04,54.0,1921.0,NaN,...,572548.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,1.947210e+05,0.398162
15171,2020,2021,지에스,지에스이앤알,1.947210e+05,지에스풍력발전,1.906718e+07,570.0,1921.0,NaN,...,572548.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,1.947210e+05,0.398162
15172,2020,2021,지에스,지에스이앤알,1.947210e+05,지에스포천그린에너지,2.402992e+07,140.0,1921.0,NaN,...,572548.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,1.947210e+05,0.398162
15173,2020,2021,지에스,지에스이앤알,1.947210e+05,영양제2풍력발전,1.802041e+07,447.0,1921.0,NaN,...,572548.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,1.947210e+05,0.398162
15174,2020,2021,지에스,지에스이앤알,1.947210e+05,영덕제1풍력발전,1.903407e+09,453.0,1921.0,NaN,...,572548.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,1.947210e+05,0.398162
15175,2020,2021,지에스,지에스이앤알,1.947210e+05,삼척그린에너지파크,2.102306e+09,123.0,1921.0,NaN,...,572548.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,1.947210e+05,0.398162
15176,2020,2021,지에스,지에스이앤알,1.947210e+05,동해국제자원터미널,2.103200e+09,134.0,1921.0,NaN,...,572548.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,1.947210e+05,0.398162
15177,2020,2021,지에스,지에스풍력발전,1.906718e+07,지에스동해전력,1.807630e+07,8544.0,8544.0,NaN,...,32835.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,1.906718e+07,0.398162
15178,2020,2021,지에스,동해그린에너지,6.866350e+05,지에스동해전력,1.807630e+07,271.0,271.0,NaN,...,385.0,NaN,0,지에스,허창수,80.0,67677.0,7.0,6.866350e+05,0.203063
15179,2020,2021,반도홀딩스,반도홀딩스,5.131640e+05,대영개발,2.105769e+07,98.0,5742.0,NaN,...,30930.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,5.131640e+05,2.000000
15180,2020,2021,반도홀딩스,반도홀딩스,5.131640e+05,대창개발,2.105769e+07,450.0,5742.0,NaN,...,30930.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,5.131640e+05,2.000000
15181,2020,2021,반도홀딩스,반도홀딩스,5.131640e+05,대현개발,2.105768e+07,37.0,5742.0,NaN,...,30930.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,5.131640e+05,2.000000
15182,2020,2021,반도홀딩스,반도홀딩스,5.131640e+05,대호개발,2.105769e+07,130.0,5742.0,NaN,...,30930.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,5.131640e+05,2.000000
15183,2020,2021,반도홀딩스,반도홀딩스,5.131640e+05,반도건설,1.301510e+07,3344.0,5742.0,NaN,...,30930.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,5.131640e+05,2.000000
15184,2020,2021,반도홀딩스,반도홀딩스,5.131640e+05,반도,1.603640e+07,254.0,5742.0,NaN,...,30930.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,5.131640e+05,2.000000
15185,2020,2021,반도홀딩스,반도홀딩스,5.131640e+05,반도종합건설,1.307819e+07,615.0,5742.0,NaN,...,30930.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,5.131640e+05,2.000000
15186,2020,2021,반도홀딩스,반도홀딩스,5.131640e+05,제니스개발,1.900950e+07,293.0,5742.0,NaN,...,30930.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,5.131640e+05,2.000000
15187,2020,2021,반도홀딩스,반도홀딩스,5.131640e+05,케이피디개발,1.900911e+07,7.0,5742.0,NaN,...,30930.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,5.131640e+05,2.000000
15188,2020,2021,반도홀딩스,반도홀딩스,5.131640e+05,하우징개발,1.900966e+07,72.0,5742.0,NaN,...,30930.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,5.131640e+05,2.000000
15189,2020,2021,반도홀딩스,반도홀딩스,5.131640e+05,한길개발,2.105760e+07,112.0,5742.0,NaN,...,30930.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,5.131640e+05,2.000000
15190,2020,2021,반도홀딩스,반도홀딩스,5.131640e+05,한숲개발,1.901028e+07,17.0,5742.0,NaN,...,30930.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,5.131640e+05,2.000000
15191,2020,2021,반도홀딩스,반도홀딩스,5.131640e+05,한영개발,2.105768e+07,163.0,5742.0,NaN,...,30930.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,5.131640e+05,2.000000
15192,2020,2021,반도홀딩스,반도홀딩스,5.131640e+05,한올개발,2.105760e+07,13.0,5742.0,NaN,...,30930.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,5.131640e+05,2.000000
15193,2020,2021,반도홀딩스,반도홀딩스,5.131640e+05,화인개발,1.900966e+07,137.0,5742.0,NaN,...,30930.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,5.131640e+05,2.000000
15194,2020,2021,반도홀딩스,더유니콘,1.301608e+07,반도건설,1.301510e+07,326.0,326.0,NaN,...,3740.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,1.301608e+07,1.000000
15195,2020,2021,반도홀딩스,반도개발,8.248610e+05,반도레저,1.301608e+07,759.0,759.0,NaN,...,12628.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,8.248610e+05,1.000000
15196,2020,2021,반도홀딩스,반도건설,1.301510e+07,대창개발,2.105769e+07,37133.0,76070.0,NaN,...,579806.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,1.301510e+07,2.000000
15197,2020,2021,반도홀딩스,반도건설,1.301510e+07,더유니콘,1.301608e+07,1084.0,76070.0,NaN,...,579806.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,1.301510e+07,2.000000
15198,2020,2021,반도홀딩스,반도건설,1.301510e+07,반도,1.603640e+07,15011.0,76070.0,NaN,...,579806.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,1.301510e+07,2.000000
15199,2020,2021,반도홀딩스,반도건설,1.301510e+07,제니스개발,1.900950e+07,8317.0,76070.0,NaN,...,579806.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,1.301510e+07,2.000000
15200,2020,2021,반도홀딩스,반도건설,1.301510e+07,호법포레,1.903109e+09,14525.0,76070.0,NaN,...,579806.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,1.301510e+07,2.000000
15201,2020,2021,반도홀딩스,에이피글로벌,1.805873e+07,대영개발,2.105769e+07,38.0,731.0,NaN,...,8613.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,1.805873e+07,1.000000
15202,2020,2021,반도홀딩스,에이피글로벌,1.805873e+07,대창개발,2.105769e+07,72.0,731.0,NaN,...,8613.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,1.805873e+07,1.000000
15203,2020,2021,반도홀딩스,에이피글로벌,1.805873e+07,더유니콘,1.301608e+07,5.0,731.0,NaN,...,8613.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,1.805873e+07,1.000000
15204,2020,2021,반도홀딩스,에이피글로벌,1.805873e+07,반도건설,1.301510e+07,435.0,731.0,NaN,...,8613.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,1.805873e+07,1.000000
15205,2020,2021,반도홀딩스,에이피글로벌,1.805873e+07,반도,1.603640e+07,71.0,731.0,NaN,...,8613.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,1.805873e+07,1.000000
15206,2020,2021,반도홀딩스,에이피글로벌,1.805873e+07,제니스개발,1.900950e+07,42.0,731.0,NaN,...,8613.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,1.805873e+07,1.000000
15207,2020,2021,반도홀딩스,에이피글로벌,1.805873e+07,한길개발,2.105760e+07,29.0,731.0,NaN,...,8613.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,1.805873e+07,1.000000
15208,2020,2021,반도홀딩스,에이피글로벌,1.805873e+07,화인개발,1.900966e+07,39.0,731.0,NaN,...,8613.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,1.805873e+07,1.000000
15209,2020,2021,반도홀딩스,동백철강,1.801407e+09,반도건설,1.301510e+07,14082.0,14082.0,NaN,...,49727.0,NaN,0,반도홀딩스,권홍사,28.0,5585.0,52.0,1.801407e+09,0.490000

In [67]:
dfTransactionsRankVr[dfTransactionsRankVr['grpname2'] == '세아']

,year,year2,grpname2,매출회사,매출회사id,매입회사,매입회사id,매출액,국내계열사계,해외계열사계,...,국내매출액,해외매출액,매출회사 상장 여부,기업집단명,동일인,계열사수,자산총액,재벌 자산 순위,firmid,ultown
12940,2020,2021,세아,세아홀딩스,1.713420e+05,세아제강지주,3.701180e+05,464.0,11768.0,20.0,...,13019.0,20.0,1,세아,이순형,29.0,9470.0,39.0,1.713420e+05,1.485492
12941,2020,2021,세아,세아홀딩스,1.713420e+05,세아제강,2.101704e+09,1413.0,11768.0,20.0,...,13019.0,20.0,1,세아,이순형,29.0,9470.0,39.0,1.713420e+05,1.485492
12942,2020,2021,세아,세아홀딩스,1.713420e+05,세아베스틸,3.815190e+05,2488.0,11768.0,20.0,...,13019.0,20.0,1,세아,이순형,29.0,9470.0,39.0,1.713420e+05,1.485492
12943,2020,2021,세아,세아홀딩스,1.713420e+05,세아창원특수강,8.259200e+04,2007.0,11768.0,20.0,...,13019.0,20.0,1,세아,이순형,29.0,9470.0,39.0,1.713420e+05,1.485492
12944,2020,2021,세아,세아홀딩스,1.713420e+05,세아특수강,3.719040e+05,1438.0,11768.0,20.0,...,13019.0,20.0,1,세아,이순형,29.0,9470.0,39.0,1.713420e+05,1.485492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13071,2020,2021,세아,브이엔티지,2.301803e+09,세아씨엠,1.902906e+09,381.0,14497.0,329.0,...,14497.0,329.0,0,세아,이순형,29.0,9470.0,39.0,2.301803e+09,1.332955
13072,2020,2021,세아,브이엔티지,2.301803e+09,동아스틸,3.455200e+04,139.0,14497.0,329.0,...,14497.0,329.0,0,세아,이순형,29.0,9470.0,39.0,2.301803e+09,1.332955
13073,2020,2021,세아,브이엔티지,2.301803e+09,씨티씨,2.103103e+09,31.0,14497.0,329.0,...,14497.0,329.0,0,세아,이순형,29.0,9470.0,39.0,2.301803e+09,1.332955
13074,2020,2021,세아,브이엔티지,2.301803e+09,세아항공방산소재,2.046270e+05,283.0,14497.0,329.0,...,14497.0,329.0,0,세아,이순형,29.0,9470.0,39.0,2.301803e+09,1.332955
13075,2020,2021,세아,브이엔티지,2.301803e+09,빈티지랩,NaN,153.0,14497.0,329.0,...,14497.0,329.0,0,세아,이순형,29.0,9470.0,39.0,2.301803e+09,1.332955

In [68]:
dfTransactionsRankVr.columns

Index(['year', 'year2', 'grpname2', '매출회사', '매출회사id', '매입회사', '매입회사id', '매출액',
       '국내계열사계', '해외계열사계', '매출액총계', '국내매출액', '해외매출액', '매출회사 상장 여부', '기업집단명',
       '동일인', '계열사수', '자산총액', '재벌 자산 순위', 'firmid', 'ultown'],
      dtype='object')

In [69]:
dfTransactionsRankVr.columns = ['year', 'year2', 'grpname2', '매출회사', '매출회사id', '매입회사', '매입회사id', '매출액',
       '국내계열사계', '해외계열사계', '매출액총계', '국내매출액', '해외매출액', '매출회사 상장 여부', '기업집단명',
       '동일인', '계열사수', '자산총액', '재벌 자산 순위', 'firmid', '매출회사 실질지분율']

In [70]:
dfTransactionsRankVr = dfTransactionsRankVr.copy().drop(columns=['firmid'])

In [71]:
def vrType(row):
    if pd.isna(row['매출회사 실질지분율']):
        return -1
    elif row['매출회사 실질지분율'] < 0.2:
        return 0
    elif row['매출회사 실질지분율'] < 0.3:
        return 1
    else:
        return 2

In [72]:
dfTransactionsRankVr['vrType'] = dfTransactionsRankVr.apply(vrType, axis=1)

In [73]:
dfTransactionsRankVr.head(50)

,year,year2,grpname2,매출회사,매출회사id,매입회사,매입회사id,매출액,국내계열사계,해외계열사계,...,국내매출액,해외매출액,매출회사 상장 여부,기업집단명,동일인,계열사수,자산총액,재벌 자산 순위,매출회사 실질지분율,vrType
0,2020,2021,대방건설,대방건설,1.588560e+05,대방하우징,2.106640e+07,153182.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
1,2020,2021,대방건설,대방건설,1.588560e+05,대방주택,2.106640e+07,103392.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
2,2020,2021,대방건설,대방건설,1.588560e+05,노블랜드,2.106640e+07,86208.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
3,2020,2021,대방건설,대방건설,1.588560e+05,디비건설,2.300768e+07,261352.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
4,2020,2021,대방건설,대방건설,1.588560e+05,디비산업개발,2.300768e+07,78658.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
5,2020,2021,대방건설,대방건설,1.588560e+05,대방이노베이션,2.300768e+07,2.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
6,2020,2021,대방건설,대방건설,1.588560e+05,대방이엔씨,1.801609e+09,1.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
7,2020,2021,대방건설,대방건설,1.588560e+05,대방개발기업,1.801609e+09,655.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
8,2020,2021,대방건설,대방건설,1.588560e+05,디비개발,1.801609e+09,5.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
9,2020,2021,대방건설,대방건설,1.588560e+05,엔비건설,1.802306e+09,73890.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
10,2020,2021,대방건설,대방건설,1.588560e+05,디비종합건설,1.801609e+09,49110.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
11,2020,2021,대방건설,대방건설,1.588560e+05,디비주택,1.801609e+09,31269.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
12,2020,2021,대방건설,대방건설,1.588560e+05,대방일산디엠시티,1.802101e+09,39058.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
13,2020,2021,대방건설,대방건설,1.588560e+05,대방덕은,1.803502e+09,54864.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
14,2020,2021,대방건설,대방건설,1.588560e+05,디엠개발,1.902707e+09,36557.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
15,2020,2021,대방건설,대방건설,1.588560e+05,대방산업개발,4.795070e+05,125.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
16,2020,2021,대방건설,대방건설,1.588560e+05,대방산업개발동탄,1.803502e+09,2383.0,970711.0,NaN,...,1557457.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
17,2020,2021,대방건설,대방산업개발,4.795070e+05,대방건설,1.588560e+05,5833.0,61693.0,NaN,...,74660.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
18,2020,2021,대방건설,대방산업개발,4.795070e+05,디엠개발,1.902707e+09,0.0,61693.0,NaN,...,74660.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
19,2020,2021,대방건설,대방산업개발,4.795070e+05,대방산업개발동탄,1.803502e+09,45128.0,61693.0,NaN,...,74660.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
20,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움,2.301508e+09,1984.0,61693.0,NaN,...,74660.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
21,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움개발,2.301508e+09,1984.0,61693.0,NaN,...,74660.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
22,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움건설,2.301508e+09,2886.0,61693.0,NaN,...,74660.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
23,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,74660.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
24,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주택개발,1.802710e+09,2886.0,61693.0,NaN,...,74660.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
25,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방건설,1.588560e+05,1929.0,3063.0,NaN,...,8119.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
26,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방하우징,2.106640e+07,20.0,3063.0,NaN,...,8119.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
27,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방주택,2.106640e+07,411.0,3063.0,NaN,...,8119.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
28,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,노블랜드,2.106640e+07,86.0,3063.0,NaN,...,8119.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
29,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,디비건설,2.300768e+07,222.0,3063.0,NaN,...,8119.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
30,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,디비종합건설,1.801609e+09,14.0,3063.0,NaN,...,8119.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
31,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방덕은,1.803502e+09,2.0,3063.0,NaN,...,8119.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
32,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,디엠개발,1.902707e+09,47.0,3063.0,NaN,...,8119.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
33,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방산업개발,4.795070e+05,332.0,3063.0,NaN,...,8119.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
34,2020,2021,대방건설,지유인터내셔날,1.301302e+09,대방건설,1.588560e+05,144.0,196.0,NaN,...,391.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
35,2020,2021,대방건설,지유인터내셔날,1.301302e+09,대방산업개발,4.795070e+05,52.0,196.0,NaN,...,391.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2
36,2020,2021,대방건설,디비일산,1.801809e+09,대방일산디엠시티,1.802101e+09,10107.0,10107.0,NaN,...,10107.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,0.000000,0
37,2020,2021,대방건설,디케이일산,1.801809e+09,대방일산디엠시티,1.802101e+09,10107.0,10107.0,NaN,...,10107.0,NaN,0,대방건설,구교운,43.0,5326.0,56.0,0.000000,0
38,2020,2021,한진,대한항공,9.900270e+05,한진칼,2.108315e+07,1158.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,0.061883,0
39,2020,2021,한진,대한항공,9.900270e+05,한진,7.101050e+05,709.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,0.061883,0
40,2020,2021,한진,대한항공,9.900270e+05,진에어,1.300692e+07,56518.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,0.061883,0
41,2020,2021,한진,대한항공,9.900270e+05,정석기업,8.116370e+05,141.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,0.061883,0
42,2020,2021,한진,대한항공,9.900270e+05,칼호텔네트워크,1.687390e+05,265.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,0.061883,0
43,2020,2021,한진,대한항공,9.900270e+05,토파스여행정보,1.059990e+05,187.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,0.061883,0
44,2020,2021,한진,대한항공,9.900270e+05,한진관광,1.909195e+07,3489.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,0.061883,0
45,2020,2021,한진,대한항공,9.900270e+05,한국공항,8.100610e+05,663.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,0.061883,0
46,2020,2021,한진,대한항공,9.900270e+05,한진정보통신,8.138770e+05,1478.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,0.061883,0
47,2020,2021,한진,대한항공,9.900270e+05,항공종합서비스,1.672550e+05,322.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,0.061883,0
48,2020,2021,한진,대한항공,9.900270e+05,싸이버스카이,2.112800e+05,44.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,0.061883,0
49,2020,2021,한진,대한항공,9.900270e+05,한국글로발로지스틱스시스템,1.275860e+05,142.0,65681.0,318.0,...,736452.0,6668554.0,1,한진,조원태,31.0,33600.0,11.0,0.061883,0

# 표 22

In [75]:
(1173 + 325) / 2399

0.6244268445185494

In [76]:
325 / 2399

0.13547311379741558

In [77]:
883 / 2399

0.36807002917882453

In [78]:
dfOV.head()

,법인등록번호,자산총액,직전사업결산일자,자본금액,자본총액,회사구분,부채총액,소속회사명,기업공개일,기업설립일,...,업종명,상시종업원수,공개년월,출력순위,대표자명,매출액,결산기일,당기순이익,기업집단명,rcmgCode
0,1.100000e+12,2.490000e+13,20210323.0,1.410000e+11,9.600000e+12,일반회사,1.530000e+13,롯데쇼핑,20060209.0,19700702,...,소매업; 자동차 제외,24963,202105,1444,강희태,8.710000e+12,20201231.0,-1.030000e+12,롯데,620068
1,1.100000e+12,1.190000e+13,20210326.0,4.040000e+11,4.420000e+12,일반회사,7.450000e+12,지에스건설,19810803.0,19691219,...,종합 건설업,6928,202105,2196,임병용,8.890000e+12,20201231.0,3.270000e+11,지에스,500143
2,1.100000e+12,6.240000e+11,20210331.0,1.685000e+10,3.520000e+11,일반회사,2.720000e+11,삼라,NaN,19690826,...,종합 건설업,12,202105,276,조유선,1.490000e+11,20201231.0,7.785100e+10,SM,500429
3,1.100000e+12,7.360000e+12,20200325.0,4.900000e+11,3.490000e+12,일반회사,3.870000e+12,한화,19760625.0,19521028,...,화학 물질 및 화학제품 제조업; 의약품 제외,5026,202105,1053,옥경석 외,4.000000e+12,20191231.0,1.290000e+11,한화,350893
4,1.100000e+12,1.630000e+12,20210326.0,1.838800e+10,7.540000e+11,일반회사,8.800000e+11,동원산업,19890307.0,19690416,...,어업,761,202105,1343,이명우,7.020000e+11,20201231.0,7.895000e+10,동원,100030

In [79]:
dfOVVr = dfOV.merge(dfVr, how='left', left_on='rcmgCode', right_on='firmid')
dfOVVr.head()

,법인등록번호,자산총액,직전사업결산일자,자본금액,자본총액,회사구분,부채총액,소속회사명,기업공개일,기업설립일,...,공개년월,출력순위,대표자명,매출액,결산기일,당기순이익,기업집단명,rcmgCode,firmid,ultown
0,1.100000e+12,2.490000e+13,20210323.0,1.410000e+11,9.600000e+12,일반회사,1.530000e+13,롯데쇼핑,20060209.0,19700702,...,202105,1444,강희태,8.710000e+12,20201231.0,-1.030000e+12,롯데,620068,620068.0,0.154261
1,1.100000e+12,1.190000e+13,20210326.0,4.040000e+11,4.420000e+12,일반회사,7.450000e+12,지에스건설,19810803.0,19691219,...,202105,2196,임병용,8.890000e+12,20201231.0,3.270000e+11,지에스,500143,500143.0,0.223957
2,1.100000e+12,6.240000e+11,20210331.0,1.685000e+10,3.520000e+11,일반회사,2.720000e+11,삼라,NaN,19690826,...,202105,276,조유선,1.490000e+11,20201231.0,7.785100e+10,SM,500429,500429.0,1.410128
3,1.100000e+12,7.360000e+12,20200325.0,4.900000e+11,3.490000e+12,일반회사,3.870000e+12,한화,19760625.0,19521028,...,202105,1053,옥경석 외,4.000000e+12,20191231.0,1.290000e+11,한화,350893,350893.0,0.319317
4,1.100000e+12,1.630000e+12,20210326.0,1.838800e+10,7.540000e+11,일반회사,8.800000e+11,동원산업,19890307.0,19690416,...,202105,1343,이명우,7.020000e+11,20201231.0,7.895000e+10,동원,100030,100030.0,0.702743

In [80]:
lstNonChaebol

['농협',
 '대우건설',
 '대우조선해양',
 '에쓰-오일',
 '케이티',
 '케이티앤지',
 '포스코',
 '한국지엠',
 '에이치엠엠',
 '한국항공우주산업',
 '쿠팡']

In [81]:
dfOVVr = dfOVVr[~dfOVVr['기업집단명'].isin(lstNonChaebol)]

In [82]:
dfOVVr['기업집단명'].unique()

array(['롯데', '지에스', 'SM', '한화', '동원', '엘지', '한진', '영풍', '엘에스', '신세계',
       '하림', '씨제이', '삼성', '유진', '삼천리', '효성', '현대자동차', '미래에셋', '태광',
       '하이트진로', '두산', '교보생명보험', '삼양', 'DB', '아모레퍼시픽', '애경', '코오롱', '동국제강',
       '한국타이어', '세아', '현대해상화재보험', '에스케이', '중앙', '오씨아이', 'IMM인베스트먼트', 'DL',
       '현대중공업', '현대백화점', '다우키움', '카카오', '금호아시아나', '중흥건설', '태영', '한국투자금융',
       '금호석유화학', '아이에스지주', '부영', '케이씨씨', '이랜드', '반도홀딩스', '한라', '에이치디씨',
       '호반건설', '넷마블', '넥슨', '대방건설', '엠디엠', '장금상선', '네이버', '셀트리온'],
      dtype=object)

In [84]:
dfOVVr.head()

,법인등록번호,자산총액,직전사업결산일자,자본금액,자본총액,회사구분,부채총액,소속회사명,기업공개일,기업설립일,...,공개년월,출력순위,대표자명,매출액,결산기일,당기순이익,기업집단명,rcmgCode,firmid,ultown
0,1.100000e+12,2.490000e+13,20210323.0,1.410000e+11,9.600000e+12,일반회사,1.530000e+13,롯데쇼핑,20060209.0,19700702,...,202105,1444,강희태,8.710000e+12,20201231.0,-1.030000e+12,롯데,620068,620068.0,0.154261
1,1.100000e+12,1.190000e+13,20210326.0,4.040000e+11,4.420000e+12,일반회사,7.450000e+12,지에스건설,19810803.0,19691219,...,202105,2196,임병용,8.890000e+12,20201231.0,3.270000e+11,지에스,500143,500143.0,0.223957
2,1.100000e+12,6.240000e+11,20210331.0,1.685000e+10,3.520000e+11,일반회사,2.720000e+11,삼라,NaN,19690826,...,202105,276,조유선,1.490000e+11,20201231.0,7.785100e+10,SM,500429,500429.0,1.410128
3,1.100000e+12,7.360000e+12,20200325.0,4.900000e+11,3.490000e+12,일반회사,3.870000e+12,한화,19760625.0,19521028,...,202105,1053,옥경석 외,4.000000e+12,20191231.0,1.290000e+11,한화,350893,350893.0,0.319317
4,1.100000e+12,1.630000e+12,20210326.0,1.838800e+10,7.540000e+11,일반회사,8.800000e+11,동원산업,19890307.0,19690416,...,202105,1343,이명우,7.020000e+11,20201231.0,7.895000e+10,동원,100030,100030.0,0.702743

In [85]:
print(len(dfOVVr[(dfOVVr['공개년월']==202105) & (~dfOVVr['ultown'].isnull())]))
print(len(dfOVVr[(dfOVVr['공개년월']==202105) & (~dfOVVr['ultown'].isnull()) & (dfOVVr['ultown'] < 0.2)]))
print(len(dfOVVr[(dfOVVr['공개년월']==202105) & (~dfOVVr['ultown'].isnull()) & (dfOVVr['ultown'] >= 0.2) & (dfOVVr['ultown'] < 0.3)]))
print(len(dfOVVr[(dfOVVr['공개년월']==202105) & (~dfOVVr['ultown'].isnull()) & (dfOVVr['ultown'] >= 0.3)]))
print(dfTransactionsRankVr.groupby(['vrType', '매출회사id'])['매입회사'].nunique().groupby('vrType').mean())
print(dfTransactionsRankVr.drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].mean())
print(dfTransactionsRankVr.drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() \
      / dfTransactionsRankVr.drop_duplicates('매출회사id').groupby(['vrType'])['매출액총계'].sum())
print(dfTransactionsRankVr.drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() \
      / dfTransactionsRankVr.drop_duplicates('매출회사id').groupby(['vrType'])['국내매출액'].sum())

2427
1217
329
881
vrType
-1    11.000000
 0     9.529259
 1     9.426087
 2     7.816135
Name: 매입회사, dtype: float64
vrType
-1     21014.000000
 0    149794.149468
 1     99271.008772
 2     47554.796591
Name: 국내계열사계, dtype: float64
vrType
-1    1.714904
 0    0.115702
 1    0.113753
 2    0.134671
dtype: float64
vrType
-1    1.755647
 0    0.211746
 1    0.148665
 2    0.178269
dtype: float64

# 표 23

In [86]:
dfOV.head()

,법인등록번호,자산총액,직전사업결산일자,자본금액,자본총액,회사구분,부채총액,소속회사명,기업공개일,기업설립일,...,업종명,상시종업원수,공개년월,출력순위,대표자명,매출액,결산기일,당기순이익,기업집단명,rcmgCode
0,1.100000e+12,2.490000e+13,20210323.0,1.410000e+11,9.600000e+12,일반회사,1.530000e+13,롯데쇼핑,20060209.0,19700702,...,소매업; 자동차 제외,24963,202105,1444,강희태,8.710000e+12,20201231.0,-1.030000e+12,롯데,620068
1,1.100000e+12,1.190000e+13,20210326.0,4.040000e+11,4.420000e+12,일반회사,7.450000e+12,지에스건설,19810803.0,19691219,...,종합 건설업,6928,202105,2196,임병용,8.890000e+12,20201231.0,3.270000e+11,지에스,500143
2,1.100000e+12,6.240000e+11,20210331.0,1.685000e+10,3.520000e+11,일반회사,2.720000e+11,삼라,NaN,19690826,...,종합 건설업,12,202105,276,조유선,1.490000e+11,20201231.0,7.785100e+10,SM,500429
3,1.100000e+12,7.360000e+12,20200325.0,4.900000e+11,3.490000e+12,일반회사,3.870000e+12,한화,19760625.0,19521028,...,화학 물질 및 화학제품 제조업; 의약품 제외,5026,202105,1053,옥경석 외,4.000000e+12,20191231.0,1.290000e+11,한화,350893
4,1.100000e+12,1.630000e+12,20210326.0,1.838800e+10,7.540000e+11,일반회사,8.800000e+11,동원산업,19890307.0,19690416,...,어업,761,202105,1343,이명우,7.020000e+11,20201231.0,7.895000e+10,동원,100030

In [121]:
len(dfOVVr[(dfOVVr['공개년월']==202105) & (~dfOVVr['ultown'].isnull())])

2427

In [88]:
len(dfOV[(~dfOV['기업집단명'].isin(lstNonChaebol)) & (dfOV['공개년월']==202105)])

2421

In [89]:
print(len(dfOVVr[(dfOVVr['공개년월']==202105) & (~dfOVVr['기업공개일'].isnull()) & (dfOVVr['ultown'] < 0.2)]))
print(len(dfOVVr[(dfOVVr['공개년월']==202105) & (~dfOVVr['기업공개일'].isnull()) & (dfOVVr['ultown'] < 0.3)]) \
      - len(dfOVVr[(dfOVVr['공개년월']==202105) & (~dfOVVr['기업공개일'].isnull()) & (dfOVVr['ultown'] < 0.2)]))
print(len(dfOVVr[(dfOVVr['공개년월']==202105) & (~dfOVVr['기업공개일'].isnull()) & (dfOVVr['ultown'] >= 0.3)]))
print(dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 1].groupby(['vrType', '매출회사id'])['매입회사'].nunique().groupby('vrType').mean())
print(dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].mean())
print(dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() \
      / dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['매출액총계'].sum())
print(dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() \
      / dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['국내매출액'].sum())

132
47
78
vrType
0    21.254098
1    20.200000
2    15.972603
Name: 매입회사, dtype: float64
vrType
0    421917.442623
1    246261.400000
2    198257.931507
Name: 국내계열사계, dtype: float64
vrType
0    0.069469
1    0.090372
2    0.142932
dtype: float64
vrType
0    0.136006
1    0.102500
2    0.221367
dtype: float64

In [126]:
132 / (132 +47 + 78), 47 / (132 +47 + 78), 78/ (132 +47 + 78)

(0.5136186770428015, 0.1828793774319066, 0.3035019455252918)

In [90]:
print(dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 1].groupby(['vrType', '매출회사id'])['매입회사'].nunique().groupby('vrType').mean())
print(dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].mean())
print(dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() \
      / dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['매출액총계'].sum())
print(dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() \
      / dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['국내매출액'].sum())

vrType
0    21.254098
1    20.200000
2    15.972603
Name: 매입회사, dtype: float64
vrType
0    421917.442623
1    246261.400000
2    198257.931507
Name: 국내계열사계, dtype: float64
vrType
0    0.069469
1    0.090372
2    0.142932
dtype: float64
vrType
0    0.136006
1    0.102500
2    0.221367
dtype: float64

# 표 24

In [91]:
print(len(dfOVVr[(dfOVVr['공개년월']==202105) & (dfOVVr['기업공개일'].isnull()) & (dfOVVr['ultown'] < 0.2)]))
print(len(dfOVVr[(dfOVVr['공개년월']==202105) & (dfOVVr['기업공개일'].isnull()) & (dfOVVr['ultown'] < 0.3)]) \
      - len(dfOVVr[(dfOVVr['공개년월']==202105) & (dfOVVr['기업공개일'].isnull()) & (dfOVVr['ultown'] < 0.2)]))
print(len(dfOVVr[(dfOVVr['공개년월']==202105) & (dfOVVr['기업공개일'].isnull()) & (dfOVVr['ultown'] >= 0.3)]))
print(dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 0].groupby(['vrType', '매출회사id'])['매입회사'].nunique().groupby('vrType').mean())
print(dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].mean())
print(dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() \
      / dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['매출액총계'].sum())
print(dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() \
      / dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['국내매출액'].sum())

1085
282
803
vrType
-1    11.000000
 0     7.318393
 1     6.805405
 2     6.521739
Name: 매입회사, dtype: float64
vrType
-1    21014.000000
 0    97097.257778
 1    63125.830601
 2    23376.051868
Name: 국내계열사계, dtype: float64
vrType
-1    1.714904
 0    0.262967
 1    0.151307
 2    0.124851
dtype: float64
vrType
-1    1.755647
 0    0.398467
 1    0.261756
 2    0.140933
dtype: float64

1518
15
207

In [128]:
1085 / (1085 + 282 + 803), 282 / (1085 + 282 + 803), 803 / (1085 + 282 + 803)

(0.5, 0.12995391705069123, 0.37004608294930874)

In [92]:
print(dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 0].groupby(['vrType', '매출회사id'])['매입회사'].nunique().groupby('vrType').mean())
print(dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].mean())
print(dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() \
      / dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['매출액총계'].sum())
print(dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() \
      / dfTransactionsRankVr[dfTransactionsRankVr['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['국내매출액'].sum())

vrType
-1    11.000000
 0     7.318393
 1     6.805405
 2     6.521739
Name: 매입회사, dtype: float64
vrType
-1    21014.000000
 0    97097.257778
 1    63125.830601
 2    23376.051868
Name: 국내계열사계, dtype: float64
vrType
-1    1.714904
 0    0.262967
 1    0.151307
 2    0.124851
dtype: float64
vrType
-1    1.755647
 0    0.398467
 1    0.261756
 2    0.140933
dtype: float64

# 표 25

In [93]:
lstR10

['현대중공업', '롯데', '에스케이', '신세계', '삼성', '엘지', '현대자동차', '씨제이', '한화', '지에스']

In [94]:
dfOVVrR10 = dfOVVr[dfOVVr['기업집단명'].isin(lstR10)]
dfTransactionsRankVrR10 = dfTransactionsRankVr[dfTransactionsRankVr['grpname2'].isin(lstR10)]

In [97]:
print(len(dfOVVrR10[(dfOVVrR10['공개년월']==202105) & (~dfOVVrR10['ultown'].isnull())]))
print(len(dfOVVrR10[(dfOVVrR10['공개년월']==202105) & (~dfOVVrR10['ultown'].isnull()) & (dfOVVrR10['ultown'] < 0.2)]))
print(len(dfOVVrR10[(dfOVVrR10['공개년월']==202105) & (~dfOVVrR10['ultown'].isnull()) & (dfOVVrR10['ultown'] >= 0.2) & (dfOVVrR10['ultown'] < 0.3)]))
print(len(dfOVVrR10[(dfOVVrR10['공개년월']==202105) & (~dfOVVrR10['ultown'].isnull()) & (dfOVVrR10['ultown'] >= 0.3)]))
print(dfTransactionsRankVrR10.groupby(['vrType', '매출회사id'])['매입회사'].nunique().groupby('vrType').mean())
print(dfTransactionsRankVrR10.drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].mean())
print(dfTransactionsRankVrR10.drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() / dfTransactionsRankVrR10.drop_duplicates('매출회사id').groupby(['vrType'])['매출액총계'].sum())
print(dfTransactionsRankVrR10.drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() / dfTransactionsRankVrR10.drop_duplicates('매출회사id').groupby(['vrType'])['국내매출액'].sum())

772
509
145
118
vrType
-1    73.000000
 0    12.435829
 1    12.475728
 2    12.485714
Name: 매입회사, dtype: float64
vrType
-1    163871.000000
 0    277419.959786
 1    174534.825243
 2    193528.200000
Name: 국내계열사계, dtype: float64
vrType
-1         inf
 0    0.127986
 1    0.118399
 2    0.208547
dtype: float64
vrType
-1         inf
 0    0.260052
 1    0.154671
 2    0.313451
dtype: float64

772
509
145
118

In [129]:
509 / 772, 145/772, 118/772

(0.6593264248704663, 0.1878238341968912, 0.15284974093264247)

# 표 26

In [99]:
print(len(dfOVVrR10[(dfOVVrR10['공개년월']==202105) & (~dfOVVrR10['기업공개일'].isnull()) & (dfOVVrR10['ultown'] < 0.2)]))
print(len(dfOVVrR10[(dfOVVrR10['공개년월']==202105) & (~dfOVVrR10['기업공개일'].isnull()) & (dfOVVrR10['ultown'] < 0.3)]) \
      - len(dfOVVrR10[(dfOVVrR10['공개년월']==202105) & (~dfOVVrR10['기업공개일'].isnull()) & (dfOVVrR10['ultown'] < 0.2)]))
print(len(dfOVVrR10[(dfOVVrR10['공개년월']==202105) & (~dfOVVrR10['기업공개일'].isnull()) & (dfOVVrR10['ultown'] >= 0.3)]))
print(dfTransactionsRankVrR10[dfTransactionsRankVrR10['매출회사 상장 여부'] == 1].groupby(['vrType', '매출회사id'])['매입회사'].nunique().groupby('vrType').mean())
print(dfTransactionsRankVrR10[dfTransactionsRankVrR10['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].mean())
print(dfTransactionsRankVrR10[dfTransactionsRankVrR10['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() / dfTransactionsRankVrR10[dfTransactionsRankVrR10['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['매출액총계'].sum())
print(dfTransactionsRankVrR10[dfTransactionsRankVrR10['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() / dfTransactionsRankVrR10[dfTransactionsRankVrR10['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['국내매출액'].sum())

76
18
11
vrType
0    26.693333
1    32.411765
2    36.200000
Name: 매입회사, dtype: float64
vrType
0    6.554662e+05
1    5.203880e+05
2    1.023319e+06
Name: 국내계열사계, dtype: float64
vrType
0    0.078457
1    0.100434
2    0.231006
dtype: float64
vrType
0    0.171840
1    0.108242
2    0.397909
dtype: float64

76
18
11

In [130]:
76 / (76 + 18 + 11), 18 / (76 + 18 + 11), 11 / (76 + 18 + 11)

(0.7238095238095238, 0.17142857142857143, 0.10476190476190476)

# 표 27

In [100]:
print(len(dfOVVrR10[(dfOVVrR10['공개년월']==202105) & (dfOVVrR10['기업공개일'].isnull()) & (dfOVVrR10['ultown'] < 0.2)]))
print(len(dfOVVrR10[(dfOVVrR10['공개년월']==202105) & (dfOVVrR10['기업공개일'].isnull()) & (dfOVVrR10['ultown'] < 0.3)]) \
      - len(dfOVVrR10[(dfOVVrR10['공개년월']==202105) & (dfOVVrR10['기업공개일'].isnull()) & (dfOVVrR10['ultown'] < 0.2)]))
print(len(dfOVVrR10[(dfOVVrR10['공개년월']==202105) & (dfOVVrR10['기업공개일'].isnull()) & (dfOVVrR10['ultown'] >= 0.3)]))
print(dfTransactionsRankVrR10[dfTransactionsRankVrR10['매출회사 상장 여부'] == 0].groupby(['vrType', '매출회사id'])['매입회사'].nunique().groupby('vrType').mean())
print(dfTransactionsRankVrR10[dfTransactionsRankVrR10['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].mean())
print(dfTransactionsRankVrR10[dfTransactionsRankVrR10['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() / dfTransactionsRankVrR10[dfTransactionsRankVrR10['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['매출액총계'].sum())
print(dfTransactionsRankVrR10[dfTransactionsRankVrR10['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() / dfTransactionsRankVrR10[dfTransactionsRankVrR10['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['국내매출액'].sum())

433
127
107
vrType
-1    73.000000
 0     8.859532
 1     8.534884
 2     8.533333
Name: 매입회사, dtype: float64
vrType
-1    163871.000000
 0    182274.097315
 1    106168.500000
 2     55229.766667
Name: 국내계열사계, dtype: float64
vrType
-1         inf
 0    0.298576
 1    0.143222
 2    0.160394
dtype: float64
vrType
-1         inf
 0    0.485708
 1    0.264665
 2    0.189344
dtype: float64

433
127
107

In [131]:
433 / (433 + 127 + 107), 127 / (433 + 127 + 107), 107 / (433 + 127 + 107)

(0.6491754122938531, 0.1904047976011994, 0.16041979010494753)

# 표 28

In [101]:
dfOVVrR5 = dfOVVr[dfOVVr['기업집단명'].isin(lstR5)]
dfTransactionsRankVrR5 = dfTransactionsRankVr[dfTransactionsRankVr['grpname2'].isin(lstR5)]

In [103]:
print(len(dfOVVrR5[(dfOVVrR5['공개년월']==202105) & (~dfOVVrR5['ultown'].isnull())]))
print(len(dfOVVrR5[(dfOVVrR5['공개년월']==202105) & (~dfOVVrR5['ultown'].isnull()) & (dfOVVrR5['ultown'] < 0.2)]))
print(len(dfOVVrR5[(dfOVVrR5['공개년월']==202105) & (~dfOVVrR5['ultown'].isnull()) & (dfOVVrR5['ultown'] >= 0.2) & (dfOVVrR5['ultown'] < 0.3)]))
print(len(dfOVVrR5[(dfOVVrR5['공개년월']==202105) & (~dfOVVrR5['ultown'].isnull()) & (dfOVVrR5['ultown'] >= 0.3)]))
print(dfTransactionsRankVrR5.groupby(['vrType', '매출회사id'])['매입회사'].nunique().groupby('vrType').mean())
print(dfTransactionsRankVrR5.drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].mean())
print(dfTransactionsRankVrR5.drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() / dfTransactionsRankVrR5.drop_duplicates('매출회사id').groupby(['vrType'])['매출액총계'].sum())
print(dfTransactionsRankVrR5.drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() / dfTransactionsRankVrR5.drop_duplicates('매출회사id').groupby(['vrType'])['국내매출액'].sum())

437
345
50
42
vrType
-1    73.000000
 0    14.098485
 1    15.684211
 2    18.125000
Name: 매입회사, dtype: float64
vrType
-1    163871.000000
 0    358980.901141
 1    258237.473684
 2    471310.958333
Name: 국내계열사계, dtype: float64
vrType
-1         inf
 0    0.130863
 1    0.160830
 2    0.235832
dtype: float64
vrType
-1         inf
 0    0.281709
 1    0.181372
 2    0.386897
dtype: float64

437
345
50
42

In [132]:
345 / 437, 50 / 437, 42/437

(0.7894736842105263, 0.11441647597254005, 0.09610983981693363)

In [104]:
print(len(dfOVVrR5[(dfOVVrR5['공개년월']==202105) & (~dfOVVrR5['기업공개일'].isnull()) & (dfOVVrR5['ultown'] < 0.2)]))
print(len(dfOVVrR5[(dfOVVrR5['공개년월']==202105) & (~dfOVVrR5['기업공개일'].isnull()) & (dfOVVrR5['ultown'] < 0.3)]) \
      - len(dfOVVrR5[(dfOVVrR5['공개년월']==202105) & (~dfOVVrR5['기업공개일'].isnull()) & (dfOVVrR5['ultown'] < 0.2)]))
print(len(dfOVVrR5[(dfOVVrR5['공개년월']==202105) & (~dfOVVrR5['기업공개일'].isnull()) & (dfOVVrR5['ultown'] >= 0.3)]))
print(dfTransactionsRankVrR5[dfTransactionsRankVrR5['매출회사 상장 여부'] == 1].groupby(['vrType', '매출회사id'])['매입회사'].nunique().groupby('vrType').mean())
print(dfTransactionsRankVrR5[dfTransactionsRankVrR5['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].mean())
print(dfTransactionsRankVrR5[dfTransactionsRankVrR5['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() / dfTransactionsRankVrR5[dfTransactionsRankVrR5['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['매출액총계'].sum())
print(dfTransactionsRankVrR5[dfTransactionsRankVrR5['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() / dfTransactionsRankVrR5[dfTransactionsRankVrR5['매출회사 상장 여부'] == 1].drop_duplicates('매출회사id').groupby(['vrType'])['국내매출액'].sum())

55
10
5
vrType
0    28.314815
1    34.222222
2    57.000000
Name: 매입회사, dtype: float64
vrType
0    8.353007e+05
1    6.701202e+05
2    2.427987e+06
Name: 국내계열사계, dtype: float64
vrType
0    0.079732
1    0.128951
2    0.248359
dtype: float64
vrType
0    0.191740
1    0.138333
2    0.442102
dtype: float64

In [133]:
55 / (55 + 10 + 5), 10 / (55 + 10 + 5), 5 / (55 + 10 + 5)

(0.7857142857142857, 0.14285714285714285, 0.07142857142857142)

In [134]:
print(len(dfOVVrR5[(dfOVVrR5['공개년월']==202105) & (dfOVVrR5['기업공개일'].isnull()) & (dfOVVrR5['ultown'] < 0.2)]))
print(len(dfOVVrR5[(dfOVVrR5['공개년월']==202105) & (dfOVVrR5['기업공개일'].isnull()) & (dfOVVrR5['ultown'] < 0.3)]) \
      - len(dfOVVrR5[(dfOVVrR5['공개년월']==202105) & (dfOVVrR5['기업공개일'].isnull()) & (dfOVVrR5['ultown'] < 0.2)]))
print(len(dfOVVrR5[(dfOVVrR5['공개년월']==202105) & (dfOVVrR5['기업공개일'].isnull()) & (dfOVVrR5['ultown'] >= 0.3)]))
print(dfTransactionsRankVrR5[dfTransactionsRankVrR5['매출회사 상장 여부'] == 0].groupby(['vrType', '매출회사id'])['매입회사'].nunique().groupby('vrType').mean())
print(dfTransactionsRankVrR5[dfTransactionsRankVrR5['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].mean())
print(dfTransactionsRankVrR5[dfTransactionsRankVrR5['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() / dfTransactionsRankVrR5[dfTransactionsRankVrR5['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['매출액총계'].sum())
print(dfTransactionsRankVrR5[dfTransactionsRankVrR5['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['국내계열사계'].sum() / dfTransactionsRankVrR5[dfTransactionsRankVrR5['매출회사 상장 여부'] == 0].drop_duplicates('매출회사id').groupby(['vrType'])['국내매출액'].sum())

290
40
37
vrType
-1    73.000000
 0    10.442857
 1     9.931034
 2    10.350000
Name: 매입회사, dtype: float64
vrType
-1    163871.000000
 0    235912.617225
 1    130411.793103
 2     79975.700000
Name: 국내계열사계, dtype: float64
vrType
-1         inf
 0    0.316599
 1    0.265505
 2    0.180541
dtype: float64
vrType
-1         inf
 0    0.493589
 1    0.359978
 2    0.220056
dtype: float64

In [111]:
290
40
37

(0.974910394265233,)

In [135]:
290/(290+40+37), 40/(290+40+37), 37/(290+40+37)

(0.7901907356948229, 0.10899182561307902, 0.1008174386920981)

# 실질지분율 차이

In [105]:
dfVr

            firmid    ultown
0     5.086000e+03  0.004698
1     1.026400e+05  0.111364
2     1.654010e+05  0.392760
3     1.663640e+05  1.000000
4     2.024870e+05  0.135900
...            ...       ...
2394  2.103503e+09  0.000000
2395  2.301709e+09  0.000000
2396  2.301803e+09  0.000000
2397  2.303403e+09  0.500000
2398  2.401403e+09  0.000000

[2399 rows x 2 columns]

In [106]:
dfTransactionsRankVr2 = dfTransactionsRankVr.merge(dfVr, how='left', left_on='매입회사id', right_on='firmid')
dfTransactionsRankVr2.head(50)

,year,year2,grpname2,매출회사,매출회사id,매입회사,매입회사id,매출액,국내계열사계,해외계열사계,...,매출회사 상장 여부,기업집단명,동일인,계열사수,자산총액,재벌 자산 순위,매출회사 실질지분율,vrType,firmid,ultown
0,2020,2021,대방건설,대방건설,1.588560e+05,대방하우징,2.106640e+07,153182.0,970711.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.106640e+07,1.000000
1,2020,2021,대방건설,대방건설,1.588560e+05,대방주택,2.106640e+07,103392.0,970711.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.106640e+07,1.000000
2,2020,2021,대방건설,대방건설,1.588560e+05,노블랜드,2.106640e+07,86208.0,970711.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.106640e+07,1.000000
3,2020,2021,대방건설,대방건설,1.588560e+05,디비건설,2.300768e+07,261352.0,970711.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.300768e+07,1.000000
4,2020,2021,대방건설,대방건설,1.588560e+05,디비산업개발,2.300768e+07,78658.0,970711.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.300768e+07,1.000000
5,2020,2021,대방건설,대방건설,1.588560e+05,대방이노베이션,2.300768e+07,2.0,970711.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.300768e+07,1.000000
6,2020,2021,대방건설,대방건설,1.588560e+05,대방이엔씨,1.801609e+09,1.0,970711.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.801609e+09,1.000000
7,2020,2021,대방건설,대방건설,1.588560e+05,대방개발기업,1.801609e+09,655.0,970711.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.801609e+09,1.000000
8,2020,2021,대방건설,대방건설,1.588560e+05,디비개발,1.801609e+09,5.0,970711.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.801609e+09,1.000000
9,2020,2021,대방건설,대방건설,1.588560e+05,엔비건설,1.802306e+09,73890.0,970711.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.802306e+09,1.000000
10,2020,2021,대방건설,대방건설,1.588560e+05,디비종합건설,1.801609e+09,49110.0,970711.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.801609e+09,1.000000
11,2020,2021,대방건설,대방건설,1.588560e+05,디비주택,1.801609e+09,31269.0,970711.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.801609e+09,1.000000
12,2020,2021,대방건설,대방건설,1.588560e+05,대방일산디엠시티,1.802101e+09,39058.0,970711.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.802101e+09,0.060000
13,2020,2021,대방건설,대방건설,1.588560e+05,대방덕은,1.803502e+09,54864.0,970711.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.803502e+09,0.950000
14,2020,2021,대방건설,대방건설,1.588560e+05,디엠개발,1.902707e+09,36557.0,970711.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.902707e+09,1.000000
15,2020,2021,대방건설,대방건설,1.588560e+05,대방산업개발,4.795070e+05,125.0,970711.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,4.795070e+05,1.000000
16,2020,2021,대방건설,대방건설,1.588560e+05,대방산업개발동탄,1.803502e+09,2383.0,970711.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.803502e+09,0.950000
17,2020,2021,대방건설,대방산업개발,4.795070e+05,대방건설,1.588560e+05,5833.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.588560e+05,1.000000
18,2020,2021,대방건설,대방산업개발,4.795070e+05,디엠개발,1.902707e+09,0.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.902707e+09,1.000000
19,2020,2021,대방건설,대방산업개발,4.795070e+05,대방산업개발동탄,1.803502e+09,45128.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.803502e+09,0.950000
20,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움,2.301508e+09,1984.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.301508e+09,1.000000
21,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움개발,2.301508e+09,1984.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.301508e+09,1.000000
22,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움건설,2.301508e+09,2886.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.301508e+09,1.000000
23,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,0.013074
24,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,1.048974
25,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,0.298080
26,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,1.000000
27,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,-2.972877
28,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,1.000000
29,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,19.928934
30,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,0.351371
31,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,0.205006
32,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,1.144746
33,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,0.841031
34,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,0.337838
35,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주택개발,1.802710e+09,2886.0,61693.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.802710e+09,1.000000
36,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방건설,1.588560e+05,1929.0,3063.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.588560e+05,1.000000
37,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방하우징,2.106640e+07,20.0,3063.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.106640e+07,1.000000
38,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방주택,2.106640e+07,411.0,3063.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.106640e+07,1.000000
39,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,노블랜드,2.106640e+07,86.0,3063.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.106640e+07,1.000000
40,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,디비건설,2.300768e+07,222.0,3063.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.300768e+07,1.000000
41,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,디비종합건설,1.801609e+09,14.0,3063.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.801609e+09,1.000000
42,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방덕은,1.803502e+09,2.0,3063.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.803502e+09,0.950000
43,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,디엠개발,1.902707e+09,47.0,3063.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.902707e+09,1.000000
44,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방산업개발,4.795070e+05,332.0,3063.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,4.795070e+05,1.000000
45,2020,2021,대방건설,지유인터내셔날,1.301302e+09,대방건설,1.588560e+05,144.0,196.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.588560e+05,1.000000
46,2020,2021,대방건설,지유인터내셔날,1.301302e+09,대방산업개발,4.795070e+05,52.0,196.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,4.795070e+05,1.000000
47,2020,2021,대방건설,디비일산,1.801809e+09,대방일산디엠시티,1.802101e+09,10107.0,10107.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,0.000000,0,1.802101e+09,0.060000
48,2020,2021,대방건설,디케이일산,1.801809e+09,대방일산디엠시티,1.802101e+09,10107.0,10107.0,NaN,...,0,대방건설,구교운,43.0,5326.0,56.0,0.000000,0,1.802101e+09,0.060000
49,2020,2021,한진,대한항공,9.900270e+05,한진칼,2.108315e+07,1158.0,65681.0,318.0,...,1,한진,조원태,31.0,33600.0,11.0,0.061883,0,2.108315e+07,0.223352

In [107]:
dfTransactionsRankVr2.columns

Index(['year', 'year2', 'grpname2', '매출회사', '매출회사id', '매입회사', '매입회사id', '매출액',
       '국내계열사계', '해외계열사계', '매출액총계', '국내매출액', '해외매출액', '매출회사 상장 여부', '기업집단명',
       '동일인', '계열사수', '자산총액', '재벌 자산 순위', '매출회사 실질지분율', 'vrType', 'firmid',
       'ultown'],
      dtype='object')

In [108]:
dfTransactionsRankVr2.columns = ['year', 'year2', 'grpname2', '매출회사', '매출회사id', '매입회사', '매입회사id', '매출액',
       '국내계열사계', '해외계열사계', '매출액총계', '국내매출액', '해외매출액', '매출회사 상장 여부', '기업집단명',
       '동일인', '계열사수', '자산총액', '재벌 자산 순위', '매출회사 실질지분율', 'vrType', 'firmid',
       '매입회사 실질지분율']

In [109]:
dfTransactionsRankVr2['실질지분율 차이'] = dfTransactionsRankVr2['매출회사 실질지분율'] - dfTransactionsRankVr2['매입회사 실질지분율']

In [110]:
dfTransactionsRankVr2.head(50)

,year,year2,grpname2,매출회사,매출회사id,매입회사,매입회사id,매출액,국내계열사계,해외계열사계,...,기업집단명,동일인,계열사수,자산총액,재벌 자산 순위,매출회사 실질지분율,vrType,firmid,매입회사 실질지분율,실질지분율 차이
0,2020,2021,대방건설,대방건설,1.588560e+05,대방하우징,2.106640e+07,153182.0,970711.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.106640e+07,1.000000,0.000000
1,2020,2021,대방건설,대방건설,1.588560e+05,대방주택,2.106640e+07,103392.0,970711.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.106640e+07,1.000000,0.000000
2,2020,2021,대방건설,대방건설,1.588560e+05,노블랜드,2.106640e+07,86208.0,970711.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.106640e+07,1.000000,0.000000
3,2020,2021,대방건설,대방건설,1.588560e+05,디비건설,2.300768e+07,261352.0,970711.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.300768e+07,1.000000,0.000000
4,2020,2021,대방건설,대방건설,1.588560e+05,디비산업개발,2.300768e+07,78658.0,970711.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.300768e+07,1.000000,0.000000
5,2020,2021,대방건설,대방건설,1.588560e+05,대방이노베이션,2.300768e+07,2.0,970711.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.300768e+07,1.000000,0.000000
6,2020,2021,대방건설,대방건설,1.588560e+05,대방이엔씨,1.801609e+09,1.0,970711.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.801609e+09,1.000000,0.000000
7,2020,2021,대방건설,대방건설,1.588560e+05,대방개발기업,1.801609e+09,655.0,970711.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.801609e+09,1.000000,0.000000
8,2020,2021,대방건설,대방건설,1.588560e+05,디비개발,1.801609e+09,5.0,970711.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.801609e+09,1.000000,0.000000
9,2020,2021,대방건설,대방건설,1.588560e+05,엔비건설,1.802306e+09,73890.0,970711.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.802306e+09,1.000000,0.000000
10,2020,2021,대방건설,대방건설,1.588560e+05,디비종합건설,1.801609e+09,49110.0,970711.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.801609e+09,1.000000,0.000000
11,2020,2021,대방건설,대방건설,1.588560e+05,디비주택,1.801609e+09,31269.0,970711.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.801609e+09,1.000000,0.000000
12,2020,2021,대방건설,대방건설,1.588560e+05,대방일산디엠시티,1.802101e+09,39058.0,970711.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.802101e+09,0.060000,0.940000
13,2020,2021,대방건설,대방건설,1.588560e+05,대방덕은,1.803502e+09,54864.0,970711.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.803502e+09,0.950000,0.050000
14,2020,2021,대방건설,대방건설,1.588560e+05,디엠개발,1.902707e+09,36557.0,970711.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.902707e+09,1.000000,0.000000
15,2020,2021,대방건설,대방건설,1.588560e+05,대방산업개발,4.795070e+05,125.0,970711.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,4.795070e+05,1.000000,0.000000
16,2020,2021,대방건설,대방건설,1.588560e+05,대방산업개발동탄,1.803502e+09,2383.0,970711.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.803502e+09,0.950000,0.050000
17,2020,2021,대방건설,대방산업개발,4.795070e+05,대방건설,1.588560e+05,5833.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.588560e+05,1.000000,0.000000
18,2020,2021,대방건설,대방산업개발,4.795070e+05,디엠개발,1.902707e+09,0.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.902707e+09,1.000000,0.000000
19,2020,2021,대방건설,대방산업개발,4.795070e+05,대방산업개발동탄,1.803502e+09,45128.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.803502e+09,0.950000,0.050000
20,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움,2.301508e+09,1984.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.301508e+09,1.000000,0.000000
21,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움개발,2.301508e+09,1984.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.301508e+09,1.000000,0.000000
22,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움건설,2.301508e+09,2886.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.301508e+09,1.000000,0.000000
23,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,0.013074,0.986926
24,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,1.048974,-0.048974
25,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,0.298080,0.701920
26,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,1.000000,0.000000
27,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,-2.972877,3.972877
28,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,1.000000,0.000000
29,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,19.928934,-18.928934
30,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,0.351371,0.648629
31,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,0.205006,0.794994
32,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,1.144746,-0.144746
33,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,0.841031,0.158969
34,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주텍,NaN,992.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,NaN,0.337838,0.662162
35,2020,2021,대방건설,대방산업개발,4.795070e+05,엘리움주택개발,1.802710e+09,2886.0,61693.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.802710e+09,1.000000,0.000000
36,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방건설,1.588560e+05,1929.0,3063.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.588560e+05,1.000000,0.000000
37,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방하우징,2.106640e+07,20.0,3063.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.106640e+07,1.000000,0.000000
38,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방주택,2.106640e+07,411.0,3063.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.106640e+07,1.000000,0.000000
39,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,노블랜드,2.106640e+07,86.0,3063.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.106640e+07,1.000000,0.000000
40,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,디비건설,2.300768e+07,222.0,3063.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,2.300768e+07,1.000000,0.000000
41,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,디비종합건설,1.801609e+09,14.0,3063.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.801609e+09,1.000000,0.000000
42,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방덕은,1.803502e+09,2.0,3063.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.803502e+09,0.950000,0.050000
43,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,디엠개발,1.902707e+09,47.0,3063.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.902707e+09,1.000000,0.000000
44,2020,2021,대방건설,대덕하우징씨스템,1.801707e+09,대방산업개발,4.795070e+05,332.0,3063.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,4.795070e+05,1.000000,0.000000
45,2020,2021,대방건설,지유인터내셔날,1.301302e+09,대방건설,1.588560e+05,144.0,196.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,1.588560e+05,1.000000,0.000000
46,2020,2021,대방건설,지유인터내셔날,1.301302e+09,대방산업개발,4.795070e+05,52.0,196.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,1.000000,2,4.795070e+05,1.000000,0.000000
47,2020,2021,대방건설,디비일산,1.801809e+09,대방일산디엠시티,1.802101e+09,10107.0,10107.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,0.000000,0,1.802101e+09,0.060000,-0.060000
48,2020,2021,대방건설,디케이일산,1.801809e+09,대방일산디엠시티,1.802101e+09,10107.0,10107.0,NaN,...,대방건설,구교운,43.0,5326.0,56.0,0.000000,0,1.802101e+09,0.060000,-0.060000
49,2020,2021,한진,대한항공,9.900270e+05,한진칼,2.108315e+07,1158.0,65681.0,318.0,...,한진,조원태,31.0,33600.0,11.0,0.061883,0,2.108315e+07,0.223352,-0.161469

In [111]:
def diffType(row):
    if pd.isna(row['실질지분율 차이']):
        return -1
    elif row['실질지분율 차이'] < 0:
        return 0
    elif row['실질지분율 차이'] < 0.03:
        return 1
    else:
        return 2

In [112]:
dfTransactionsRankVr2['diffType'] = dfTransactionsRankVr2.apply(diffType, axis=1)

In [113]:
dfTransactionsRankVr2R10 = dfTransactionsRankVr2[dfTransactionsRankVr2['grpname2'].isin(lstR10)]
dfTransactionsRankVr2R5 = dfTransactionsRankVr2[dfTransactionsRankVr2['grpname2'].isin(lstR5)]

# 표 31

In [114]:
dfTransactionsRankVr2.groupby('diffType').size()

diffType
-1      172
 0    16943
 1     3835
 2    10004
dtype: int64

In [115]:
len(dfTransactionsRankVr2)

30954

In [116]:
dfTransactionsRankVr2.groupby('diffType')['매출액'].sum() / dfTransactionsRankVr2.groupby('diffType').size()

diffType
-1     1672.581395
 0    13292.193929
 1    18464.707419
 2    12351.604492
dtype: float64

# 표 32

In [117]:
dfTransactionsRankVr2R10.groupby('diffType').size()

diffType
-1     122
 0    8664
 1    1656
 2    4738
dtype: int64

In [118]:
dfTransactionsRankVr2R10.groupby('diffType')['매출액'].sum() / dfTransactionsRankVr2R10.groupby('diffType').size()

diffType
-1     2185.737705
 0    22272.811588
 1    35458.704106
 2    21826.702195
dtype: float64

# 표 33

In [119]:
dfTransactionsRankVr2R5.groupby('diffType').size()

diffType
-1     122
 0    5681
 1    1114
 2    2941
dtype: int64

In [120]:
dfTransactionsRankVr2R5.groupby('diffType')['매출액'].sum() / dfTransactionsRankVr2R5.groupby('diffType').size()

diffType
-1     2185.737705
 0    10702.313149
 1    42733.545781
 2    22826.493370
dtype: float64